`timescale 1ns / 1ps
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// config_regs_tb.sv — Auto-generated by Phase 1 Validation Agent
//
// Tests:
//   1. Reset values for all 11 registers
//   2. Write/readback for all RW registers
//   3. Invalid address error response
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
module config_regs_tb;

    localparam real CLK_PERIOD = 5.0;
    logic clk = 0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // ── DUT signals ──
    logic        rst_n;
    logic [7:0]  csr_addr_i;
    logic [31:0] csr_dat_i;
    logic        csr_we_i;
    logic        csr_stb_i;
    logic [31:0] csr_dat_o;
    logic        csr_ack_o;
    logic        csr_err_o;

    // Timing config outputs (directly from spec)
    // (connected but not exhaustively checked in this TB — static validation covers them)

    config_regs dut (
        .clk       (clk),
        .rst_n     (rst_n),
        .csr_addr_i(csr_addr_i),
        .csr_dat_i (csr_dat_i),
        .csr_we_i  (csr_we_i),
        .csr_stb_i (csr_stb_i),
        .csr_dat_o (csr_dat_o),
        .csr_ack_o (csr_ack_o),
        .csr_err_o (csr_err_o)
    );

    // CTRL_STATUS @ 0x00  access=RO  reset=0x00000000
    // CTRL_CONFIG @ 0x04  access=RW  reset=0x00000009
    // TIMING_0 @ 0x08  access=RW  reset=0x271C0B0B
    // TIMING_1 @ 0x0C  access=RW  reset=0x80200606
    // TIMING_2 @ 0x10  access=RW  reset=0x080B060C
    // TIMING_3 @ 0x14  access=RW  reset=0x00186004
    // REFRESH_CONFIG @ 0x18  access=RW  reset=0x00000168
    // ERROR_STATUS @ 0x1C  access=RW1C  reset=0x00000000
    // BIST_CONFIG @ 0x20  access=RW  reset=0x00000000
    // BIST_ADDR_START @ 0x24  access=RW  reset=0x00000000
    // BIST_ADDR_END @ 0x28  access=RW  reset=0x1FFFFFFF

    // ── Test infrastructure ──
    int pass_count = 0;
    int fail_count = 0;
    int total_tests = 0;

    task check(string name, logic condition);
        total_tests++;
        if (condition) begin
            pass_count++;
            $display("  ✓ PASS  %s", name);
        end else begin
            fail_count++;
            $display("  ✗ FAIL  %s", name);
        end
    endtask

    logic [31:0] rdata;

    task csr_write(input [7:0] addr, input [31:0] data);
        @(posedge clk);
        csr_addr_i = addr;
        csr_dat_i  = data;
        csr_we_i   = 1;
        csr_stb_i  = 1;
        @(posedge clk);
        wait(csr_ack_o || csr_err_o);
        @(posedge clk);
        csr_stb_i = 0;
        csr_we_i  = 0;
    endtask

    task csr_read(input [7:0] addr, output [31:0] data);
        @(posedge clk);
        csr_addr_i = addr;
        csr_we_i   = 0;
        csr_stb_i  = 1;
        @(posedge clk);
        wait(csr_ack_o || csr_err_o);
        data = csr_dat_o;
        @(posedge clk);
        csr_stb_i = 0;
    endtask

    initial begin
        $display("");
        $display("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        $display("  config_regs_tb — CSR Register Verification");
        $display("  11 registers, 32-bit data bus");
        $display("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

        // Init
        rst_n = 0;
        csr_stb_i = 0;
        csr_we_i  = 0;
        csr_addr_i = 0;
        csr_dat_i  = 0;
        repeat (5) @(posedge clk);
        rst_n = 1;
        repeat (2) @(posedge clk);

        // ── Reset value checks ──
        $display("");
        $display("  ── Reset Values ──");

        csr_read(8'h00, rdata);
        check($sformatf("CTRL_STATUS reset = 0x%08X", rdata), rdata == 32'h00000000);
        csr_read(8'h04, rdata);
        check($sformatf("CTRL_CONFIG reset = 0x%08X", rdata), rdata == 32'h00000009);
        csr_read(8'h08, rdata);
        check($sformatf("TIMING_0 reset = 0x%08X", rdata), rdata == 32'h271C0B0B);
        csr_read(8'h0C, rdata);
        check($sformatf("TIMING_1 reset = 0x%08X", rdata), rdata == 32'h80200606);
        csr_read(8'h10, rdata);
        check($sformatf("TIMING_2 reset = 0x%08X", rdata), rdata == 32'h080B060C);
        csr_read(8'h14, rdata);
        check($sformatf("TIMING_3 reset = 0x%08X", rdata), rdata == 32'h00186004);
        csr_read(8'h18, rdata);
        check($sformatf("REFRESH_CONFIG reset = 0x%08X", rdata), rdata == 32'h00000168);
        csr_read(8'h1C, rdata);
        check($sformatf("ERROR_STATUS reset = 0x%08X", rdata), rdata == 32'h00000000);
        csr_read(8'h20, rdata);
        check($sformatf("BIST_CONFIG reset = 0x%08X", rdata), rdata == 32'h00000000);
        csr_read(8'h24, rdata);
        check($sformatf("BIST_ADDR_START reset = 0x%08X", rdata), rdata == 32'h00000000);
        csr_read(8'h28, rdata);
        check($sformatf("BIST_ADDR_END reset = 0x%08X", rdata), rdata == 32'h1FFFFFFF);

        // ── Write/Readback ──
        $display("");
        $display("  ── Write/Readback ──");

        // Write/read CTRL_CONFIG
        csr_write(8'h04, 32'hA5A5A5A5);
        csr_read(8'h04, rdata);
        check("CTRL_CONFIG write/readback", rdata == 32'hA5A5A5A5);

        // Write/read TIMING_0
        csr_write(8'h08, 32'hA5A5A5A5);
        csr_read(8'h08, rdata);
        check("TIMING_0 write/readback", rdata == 32'hA5A5A5A5);

        // Write/read TIMING_1
        csr_write(8'h0C, 32'hA5A5A5A5);
        csr_read(8'h0C, rdata);
        check("TIMING_1 write/readback", rdata == 32'hA5A5A5A5);

        // Write/read TIMING_2
        csr_write(8'h10, 32'hA5A5A5A5);
        csr_read(8'h10, rdata);
        check("TIMING_2 write/readback", rdata == 32'hA5A5A5A5);

        // Write/read TIMING_3
        csr_write(8'h14, 32'hA5A5A5A5);
        csr_read(8'h14, rdata);
        check("TIMING_3 write/readback", rdata == 32'hA5A5A5A5);

        // Write/read REFRESH_CONFIG
        csr_write(8'h18, 32'hA5A5A5A5);
        csr_read(8'h18, rdata);
        check("REFRESH_CONFIG write/readback", rdata == 32'hA5A5A5A5);

        // Write/read BIST_CONFIG
        csr_write(8'h20, 32'hA5A5A5A5);
        csr_read(8'h20, rdata);
        check("BIST_CONFIG write/readback", rdata == 32'hA5A5A5A5);

        // Write/read BIST_ADDR_START
        csr_write(8'h24, 32'hA5A5A5A5);
        csr_read(8'h24, rdata);
        check("BIST_ADDR_START write/readback", rdata == 32'hA5A5A5A5);

        // Write/read BIST_ADDR_END
        csr_write(8'h28, 32'hA5A5A5A5);
        csr_read(8'h28, rdata);
        check("BIST_ADDR_END write/readback", rdata == 32'hA5A5A5A5);

        // ── Invalid address ──
        $display("");
        $display("  ── Error Handling ──");
        @(posedge clk);
        csr_addr_i = 8'hFF;  // invalid
        csr_stb_i  = 1;
        csr_we_i   = 0;
        @(posedge clk);
        repeat (3) @(posedge clk);
        check("Invalid address returns error", csr_err_o === 1'b1);
        csr_stb_i = 0;

        // ── Summary ──
        $display("");
        $display("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        if (fail_count == 0)
            $display("  ✓ ALL %0d TESTS PASSED", total_tests);
        else
            $display("  ✗ %0d/%0d TESTS FAILED", fail_count, total_tests);
        $display("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        $display("");
        $finish;
    end

endmodule
