////////////////////////////////////////////////////////////////////////////////
// Event-Mode Testbench for path_08_init_to_cal
// Generated by event_tb_codegen.py — DO NOT EDIT BY HAND
//
// Vector file format: OO PPPPPPPP DDDDDDDD EEEEEEEE
//   00 = reset        (calls handle_reset)
//   03 = step P       (advances P cycles via event_tick)
//   04 = wait_for     (P[7:0]=sig, D=value, E=timeout)
//   05 = check_at     (P[7:0]=sig, D=value, E=target_cycle)
//   06 = check_not_yet(P[7:0]=sig, D=value, E=until_cycle)
//   07 = expect_hs    (P[7:0]=valid, P[15:8]=ready, E=timeout)
//   08 = check_order  (P[7:0]=first, P[15:8]=second, E=min_gap)
//   09 = event_start
////////////////////////////////////////////////////////////////////////////////

`timescale 1ns/1ps

module path_08_init_to_cal_tb;

    // ---- Clock generation ----
    logic clk;
    logic rst_n;
    initial clk = 1'b0;
    always #5 clk = ~clk;  // 100 MHz


    // ==========================================================================
    // DUT Wiring (from wiring_template.sv)
    // ==========================================================================

    // ---- Internal wires (between blocks) ----
    logic        init_done;

    // ---- Testbench-driven inputs ----
    logic        enable;
    logic        zqcs_ack;

    // ---- Testbench-monitored outputs ----
    logic        init_fail;
    logic        init_cmd_valid;
    logic [3:0] init_cmd;
    logic [14:0] init_addr;
    logic [2:0] init_bank;
    logic        init_cke;
    logic        init_reset_n;
    logic [3:0] init_state;
    logic        cal_done;
    logic        cal_fail;
    logic        zqcs_req;

    // ---- Module instantiations ----
    init_fsm u_init_fsm (
        .clk(clk),
        .rst_n(rst_n),
        .enable(enable),
        .init_addr(init_addr),
        .init_bank(init_bank),
        .init_cke(init_cke),
        .init_cmd(init_cmd),
        .init_cmd_valid(init_cmd_valid),
        .init_done(init_done),
        .init_fail(init_fail),
        .init_reset_n(init_reset_n),
        .init_state(init_state)
    );

    calibration u_calibration (
        .clk(clk),
        .rst_n(rst_n),
        .cal_done(cal_done),
        .cal_fail(cal_fail),
        .init_done(init_done),
        .zqcs_ack(zqcs_ack),
        .zqcs_req(zqcs_req)
    );


    // ==========================================================================
    // Event-Mode Task Library
    // ==========================================================================
    // ==========================================================================
    // Event-Mode Verification Task Library
    // ==========================================================================
    // SPEC AUTHORING GUIDANCE:
    // - Prefer sampling FSM state registers (e.g. init_fsm.init_state) over
    //   chaining command-output handshakes. One wait_for on the terminal state
    //   is clearer than 8 expect_handshakes on intermediate MRS commands.
    // - Use check_not_yet immediately after event_start() to guard JEDEC
    //   minimum-time constraints (e.g. init_done >= 140000 cycles from start).
    // - check_order between two wait_for'd events validates relative ordering
    //   without depending on absolute cycle counts.
    // ==========================================================================

    localparam int MAX_SIG_ID = 32;

    // Per-signal arrival tracking. arrival_cycle[id] == -1 means "not yet seen".
    int  arrival_cycle [0:MAX_SIG_ID-1];
    int  arrival_value [0:MAX_SIG_ID-1];
    int  sim_cycle;  // cycles since last event_start() (or event_reset())

    // --- Latching predicate tracking (Stage 4 bugfix) ---
    // first_seen[id] is the first latch_cycle at which sample_signal(id) was
    // nonzero. Set to -1 until observed. This lets wait_for capture narrow
    // 1-cycle predicates even when called after the pulse has already fired.
    int  first_seen [0:MAX_SIG_ID-1];
    int  latch_cycle;       // advances every posedge after latch_enabled
    bit  latch_enabled;     // gated by event_start()

    // Codegen'd per-path by Stage 2. Returns current value of signal `id`
    // as a 32-bit word. Stub returns 0 so template compiles standalone.
    function automatic logic [31:0] sample_signal(input int id);
        sample_signal = 32'h0;
        case (id)
            // sig 0: init_state
            0: sample_signal = {28'b0, u_init_fsm.init_state};
            // sig 1: init_done
            1: sample_signal = {31'b0, u_init_fsm.init_done};
            // sig 2: init_fail
            2: sample_signal = {31'b0, u_init_fsm.init_fail};
            // sig 3: init_cke
            3: sample_signal = {31'b0, u_init_fsm.init_cke};
            // sig 4: init_reset_n
            4: sample_signal = {31'b0, u_init_fsm.init_reset_n};
            // sig 5: init_cmd_valid
            5: sample_signal = {31'b0, u_init_fsm.init_cmd_valid};
            // sig 6: init_cmd
            6: sample_signal = {28'b0, u_init_fsm.init_cmd};
            // sig 7: init_bank
            7: sample_signal = {29'b0, u_init_fsm.init_bank};
            // sig 8: cal_done
            8: sample_signal = {31'b0, u_calibration.cal_done};
            // sig 9: cal_fail
            9: sample_signal = {31'b0, u_calibration.cal_fail};
            // sig 10: cal_init_done_input
            10: sample_signal = {31'b0, u_calibration.init_done};
            // sig 11: state_idle
            11: sample_signal = (u_init_fsm.init_state == 4'd0) ? 32'h1 : 32'h0;
            // sig 12: state_reset_low
            12: sample_signal = (u_init_fsm.init_state == 4'd1) ? 32'h1 : 32'h0;
            // sig 13: state_reset_high
            13: sample_signal = (u_init_fsm.init_state == 4'd2) ? 32'h1 : 32'h0;
            // sig 14: state_cke_wait
            14: sample_signal = (u_init_fsm.init_state == 4'd3) ? 32'h1 : 32'h0;
            // sig 15: state_mr2
            15: sample_signal = (u_init_fsm.init_state == 4'd4) ? 32'h1 : 32'h0;
            // sig 16: state_mr3
            16: sample_signal = (u_init_fsm.init_state == 4'd6) ? 32'h1 : 32'h0;
            // sig 17: state_mr1
            17: sample_signal = (u_init_fsm.init_state == 4'd8) ? 32'h1 : 32'h0;
            // sig 18: state_mr0
            18: sample_signal = (u_init_fsm.init_state == 4'd10) ? 32'h1 : 32'h0;
            // sig 19: state_zqcl
            19: sample_signal = (u_init_fsm.init_state == 4'd12) ? 32'h1 : 32'h0;
            // sig 20: state_done
            20: sample_signal = (u_init_fsm.init_state == 4'd14) ? 32'h1 : 32'h0;
            // sig 21: mrs_mr2_issued
            21: sample_signal = (u_init_fsm.init_cmd_valid && u_init_fsm.init_cmd == 4'b0000 && u_init_fsm.init_bank == 3'd2) ? 32'h1 : 32'h0;
            // sig 22: mrs_mr3_issued
            22: sample_signal = (u_init_fsm.init_cmd_valid && u_init_fsm.init_cmd == 4'b0000 && u_init_fsm.init_bank == 3'd3) ? 32'h1 : 32'h0;
            // sig 23: mrs_mr1_issued
            23: sample_signal = (u_init_fsm.init_cmd_valid && u_init_fsm.init_cmd == 4'b0000 && u_init_fsm.init_bank == 3'd1) ? 32'h1 : 32'h0;
            // sig 24: mrs_mr0_issued
            24: sample_signal = (u_init_fsm.init_cmd_valid && u_init_fsm.init_cmd == 4'b0000 && u_init_fsm.init_bank == 3'd0) ? 32'h1 : 32'h0;
            // sig 25: zqcl_issued
            25: sample_signal = (u_init_fsm.init_cmd_valid && u_init_fsm.init_cmd == 4'b0110) ? 32'h1 : 32'h0;
            // sig 26: reset_asserted
            26: sample_signal = (u_init_fsm.init_reset_n == 1'b0) ? 32'h1 : 32'h0;
            // sig 27: cke_high
            27: sample_signal = (u_init_fsm.init_cke == 1'b1) ? 32'h1 : 32'h0;
            // sig 28: init_done_and_cal_done
            28: sample_signal = (u_init_fsm.init_done && u_calibration.cal_done) ? 32'h1 : 32'h0;
            default: sample_signal = 32'h0;
        endcase
    endfunction

    // Latch block: records first cycle each signal is nonzero. Runs on every
    // posedge once latch_enabled is set by event_start(). Gives wait_for a
    // reliable fast path for 1-cycle predicates and already-asserted signals.
    always_ff @(posedge clk) begin
        if (latch_enabled) begin
            latch_cycle <= latch_cycle + 1;
            for (int _li = 0; _li < MAX_SIG_ID; _li++) begin
                if (first_seen[_li] < 0 && sample_signal(_li) != 32'h0) begin
                    first_seen[_li] <= latch_cycle + 1;
                end
            end
        end
    end

    task automatic event_reset();
        for (int i = 0; i < MAX_SIG_ID; i++) begin
            arrival_cycle[i] = -1;
            arrival_value[i] = 0;
            first_seen[i] = -1;
        end
        sim_cycle = 0;
        latch_cycle = 0;
        latch_enabled = 1'b0;
    endtask

    // Pulse the DUT's start signal (e.g. init_fsm.enable) and zero sim_cycle
    // at THAT moment. Codegen'd per-path; stub is a no-op for paths with no
    // autonomous start (e.g. CSR-only tail paths).
    task automatic event_start();
        enable = 1'b1;
        for (int _si = 0; _si < MAX_SIG_ID; _si++) first_seen[_si] = -1;
        sim_cycle = 0;
        latch_cycle = 0;
        latch_enabled = 1'b1;
    endtask

    // CRITICAL INVARIANT: any code that advances simulation time outside this
    // task will cause sim_cycle drift. The opcode 03 (step) dispatch in Stage 4
    // MUST call this task in a loop, NOT bare @(posedge clk). Mixing modes
    // without going through event_tick() will silently break check_at and
    // check_not_yet timing relative to event_start().
    task automatic event_tick();
        @(posedge clk);
        sim_cycle = sim_cycle + 1;
    endtask

    // --------------------------------------------------------------------------
    // wait_for: block until sample_signal(id) == value, up to `timeout` cycles.
    // Records arrival on success. Counts as one test.
    // --------------------------------------------------------------------------
    task automatic wait_for(
        input int          sig_id,
        input logic [31:0] value,
        input int          timeout,
        input int          vec_num,
        inout int          pass_count,
        inout int          fail_count,
        inout int          total_tests
    );
        int waited;
        logic [31:0] obs;
        bit done;
        waited = 0;
        done = 1'b0;
        total_tests = total_tests + 1;

        // FAST PATH (value == 1): consult the latch. If the signal was ever
        // observed nonzero, use the recorded fire cycle — don't re-sample.
        // This handles narrow 1-cycle predicates and already-latched signals
        // correctly regardless of when wait_for was called.
        if (value == 32'h1 && first_seen[sig_id] >= 0) begin
            arrival_cycle[sig_id] = first_seen[sig_id];
            arrival_value[sig_id] = 32'h1;
            pass_count = pass_count + 1;
            done = 1'b1;
        end

        while (!done) begin
            if (value == 32'h1) begin
                // Poll the latch each tick — parallel latch block records
                // first_seen[sig_id] the instant the predicate fires.
                if (first_seen[sig_id] >= 0) begin
                    arrival_cycle[sig_id] = first_seen[sig_id];
                    arrival_value[sig_id] = 32'h1;
                    pass_count = pass_count + 1;
                    done = 1'b1;
                end else if (waited >= timeout) begin
                    fail_count = fail_count + 1;
                    $display("WAIT_FOR TIMEOUT vec=%0d sig=%0d expected=0x%08X after=%0d",
                             vec_num, sig_id, value, waited);
                    done = 1'b1;
                end else begin
                    event_tick();
                    waited = waited + 1;
                end
            end else begin
                // Non-1 target (rare: "wait for signal to be deasserted"):
                // live-sample fallback, unchanged from the original semantics.
                obs = sample_signal(sig_id);
                if (obs === value) begin
                    arrival_cycle[sig_id] = sim_cycle;
                    arrival_value[sig_id] = obs;
                    pass_count = pass_count + 1;
                    done = 1'b1;
                end else if (waited >= timeout) begin
                    fail_count = fail_count + 1;
                    $display("WAIT_FOR TIMEOUT vec=%0d sig=%0d expected=0x%08X last=0x%08X after=%0d",
                             vec_num, sig_id, value, obs, waited);
                    done = 1'b1;
                end else begin
                    event_tick();
                    waited = waited + 1;
                end
            end
        end
    endtask

    // --------------------------------------------------------------------------
    // check_at: advance to absolute cycle `target` (relative to last event_start)
    // and verify sample_signal(id) == value.
    // --------------------------------------------------------------------------
    task automatic check_at(
        input int          sig_id,
        input logic [31:0] value,
        input int          target,
        input int          vec_num,
        inout int          pass_count,
        inout int          fail_count,
        inout int          total_tests
    );
        logic [31:0] obs;
        total_tests = total_tests + 1;
        while (sim_cycle < target) event_tick();
        obs = sample_signal(sig_id);
        if (obs === value) begin
            pass_count = pass_count + 1;
        end else begin
            fail_count = fail_count + 1;
            $display("CHECK_AT MISMATCH vec=%0d sig=%0d cycle=%0d expected=0x%08X actual=0x%08X",
                     vec_num, sig_id, target, value, obs);
        end
    endtask

    // --------------------------------------------------------------------------
    // check_not_yet: from current sim_cycle through `until_cycle`, verify the
    // signal never equals `value`. JEDEC minimum-time guard. NB: `until` is a
    // SystemVerilog reserved word, hence `until_cycle`.
    // --------------------------------------------------------------------------
    task automatic check_not_yet(
        input int          sig_id,
        input logic [31:0] value,
        input int          until_cycle,
        input int          vec_num,
        inout int          pass_count,
        inout int          fail_count,
        inout int          total_tests
    );
        logic [31:0] obs;
        bit violated;
        total_tests = total_tests + 1;
        violated = 1'b0;
        while (sim_cycle < until_cycle) begin
            if (!violated) begin
                obs = sample_signal(sig_id);
                if (obs === value) begin
                    fail_count = fail_count + 1;
                    $display("CHECK_NOT_YET VIOLATION vec=%0d sig=%0d value=0x%08X arrived=%0d min=%0d",
                             vec_num, sig_id, value, sim_cycle, until_cycle);
                    violated = 1'b1;
                end
            end
            event_tick();
        end
        if (!violated) pass_count = pass_count + 1;
    endtask

    // --------------------------------------------------------------------------
    // expect_handshake: wait for valid && ready on the same posedge. Records
    // arrival under valid_id.
    // --------------------------------------------------------------------------
    task automatic expect_handshake(
        input int valid_id,
        input int ready_id,
        input int timeout,
        input int vec_num,
        inout int pass_count,
        inout int fail_count,
        inout int total_tests
    );
        int waited;
        bit done;
        waited = 0;
        done = 1'b0;
        total_tests = total_tests + 1;
        while (!done) begin
            if (sample_signal(valid_id) === 32'h1 &&
                sample_signal(ready_id) === 32'h1) begin
                arrival_cycle[valid_id] = sim_cycle;
                arrival_value[valid_id] = 1;
                pass_count = pass_count + 1;
                done = 1'b1;
            end else if (waited >= timeout) begin
                fail_count = fail_count + 1;
                $display("HANDSHAKE TIMEOUT vec=%0d valid_sig=%0d ready_sig=%0d after=%0d",
                         vec_num, valid_id, ready_id, waited);
                done = 1'b1;
            end else begin
                event_tick();
                waited = waited + 1;
            end
        end
    endtask

    // --------------------------------------------------------------------------
    // check_order: verify two prior wait_for/expect_handshake events occurred
    // in the right order with at least `min_gap` cycles between them.
    // --------------------------------------------------------------------------
    task automatic check_order(
        input int first_id,
        input int second_id,
        input int min_gap,
        input int vec_num,
        inout int pass_count,
        inout int fail_count,
        inout int total_tests
    );
        int gap;
        bit done;
        done = 1'b0;
        total_tests = total_tests + 1;
        if (arrival_cycle[first_id] < 0) begin
            fail_count = fail_count + 1;
            $display("CHECK_ORDER MISSING vec=%0d first_sig=%0d never observed", vec_num, first_id);
            done = 1'b1;
        end
        if (!done && arrival_cycle[second_id] < 0) begin
            fail_count = fail_count + 1;
            $display("CHECK_ORDER MISSING vec=%0d second_sig=%0d never observed", vec_num, second_id);
            done = 1'b1;
        end
        if (!done) begin
            gap = arrival_cycle[second_id] - arrival_cycle[first_id];
            if (gap < min_gap) begin
                fail_count = fail_count + 1;
                $display("CHECK_ORDER VIOLATION vec=%0d first=%0d@%0d second=%0d@%0d gap=%0d min=%0d",
                         vec_num, first_id, arrival_cycle[first_id],
                         second_id, arrival_cycle[second_id], gap, min_gap);
            end else begin
                pass_count = pass_count + 1;
            end
        end
    endtask


    // ==========================================================================
    // Reset Handler
    // ==========================================================================
    task automatic handle_reset();
        rst_n = 1'b0;
        repeat(4) @(posedge clk);
        rst_n = 1'b1;
        @(posedge clk);
        event_reset();
    endtask

    // ==========================================================================
    // Vector File Dispatch Loop
    // ==========================================================================
    integer vec_file;
    integer n_matched;
    integer fgets_result;
    integer line_num;
    integer pc, fc, tt;
    integer k;
    reg [7:0]  op;
    reg [31:0] p_field;
    reg [31:0] d_field;
    reg [31:0] e_field;
    reg [1023:0] line_buf;

    initial begin
        pc = 0;
        fc = 0;
        tt = 0;
        line_num = 0;
        rst_n = 1'b0;

        vec_file = $fopen("path_08_init_to_cal_vectors.hex", "r");
        if (vec_file == 0) begin
            $display("ERROR: Could not open vector file path_08_init_to_cal_vectors.hex");
            $finish;
        end

        fgets_result = 1;
        while (fgets_result != 0) begin
            line_buf = 0;
            fgets_result = $fgets(line_buf, vec_file);
            if (fgets_result == 0) begin
                // EOF
            end else begin
                line_num = line_num + 1;
                // $sscanf returns the number of successful matches. Comment
                // lines ("// ...") and blanks return 0 — we simply skip them
                // by not entering the case block.
                n_matched = $sscanf(line_buf, "%h %h %h %h", op, p_field, d_field, e_field);
                if (n_matched == 4) begin
                    case (op)
                        8'h00: handle_reset();
                        8'h03: begin
                            for (k = 0; k < p_field; k = k + 1) event_tick();
                        end
                        8'h04: wait_for(p_field[7:0], d_field, e_field, line_num, pc, fc, tt);
                        8'h05: check_at(p_field[7:0], d_field, e_field, line_num, pc, fc, tt);
                        8'h06: check_not_yet(p_field[7:0], d_field, e_field, line_num, pc, fc, tt);
                        8'h07: expect_handshake(p_field[7:0], p_field[15:8], e_field, line_num, pc, fc, tt);
                        8'h08: check_order(p_field[7:0], p_field[15:8], e_field, line_num, pc, fc, tt);
                        8'h09: event_start();
                        default: $display("UNKNOWN OPCODE 0x%02X at line %0d", op, line_num);
                    endcase
                end
            end
        end

        $fclose(vec_file);
        $display("=========================================");
        $display("path_08_init_to_cal EVENT-MODE SUMMARY");
        $display("  total_tests: %0d", tt);
        $display("  pass_count:  %0d", pc);
        $display("  fail_count:  %0d", fc);
        if (fc == 0 && tt > 0) $display("  RESULT: PASS");
        else                   $display("  RESULT: FAIL");
        $display("=========================================");
        $finish;
    end

    // Watchdog
    initial begin
        #(800000 * 10);  // 10 ns per cycle @ 100 MHz ctrl clock
        $display("WATCHDOG TIMEOUT after 800000 cycles");
        $display("path_08_init_to_cal EVENT-MODE SUMMARY");
        $display("  total_tests: %0d", tt);
        $display("  pass_count:  %0d", pc);
        $display("  fail_count:  %0d", fc);
        $display("  RESULT: WATCHDOG_FAIL");
        $finish;
    end

endmodule
