#!/usr/bin/env python3
"""
schema_gen.py — resolve transaction schemas from the spec and manifests
========================================================================
Turns interface_catalog.json (which ports form each transaction — data) into
fully resolved schemas (with widths and directions) by consulting the
frontend manifests and the spec. No width, direction, or address constant is
ever written by hand.

Spec-swappability is enforced by failing loudly: if a catalog port does not
exist in the named block's manifest, or a direction contradicts how the field
is used, generation stops with an error naming the mismatch. A new design
either resolves cleanly or tells you exactly what changed.

Outputs Validation/txn/generated/schemas.json, consumed by:
  * monitor codegen        (which pins to sample, how wide)
  * the trace extractor    (how to parse TXN lines)
  * the scoreboard         (field sets for matching)
  * the refmodel agent     (quoted into its prompt so generated predictors
                            speak the same vocabulary)

Usage:
    python3 Validation/txn/schema_gen.py            # generate + print summary
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
CATALOG = os.path.join(HERE, "interface_catalog.json")
OUT_DIR = os.path.join(HERE, "generated")
FRONTEND_ROOT = os.path.join(ROOT, "Frontend", "OutputFolders")
SPEC_PATH = os.path.join(ROOT, "Validation", "spec",
                         "llmmc_microarchitecturespec_filled.json")


class SchemaError(Exception):
    pass


def discover_manifest(frontend_root: str, block: str):
    """Find <block>_manifest.json under the frontend output tree.

    The frontend emits a manifest per RTL generation phase AND a copy into
    each lint report directory, so several generations of the same block can
    be on disk at once. Walk order is not defined, so picking "the first one
    found" silently binds validation to whichever copy the filesystem
    happened to yield — today they agree, but the moment the frontend
    regenerates they will not, and the failure would be invisible.

    Sort deterministically and prefer the most recently modified copy, which
    is the current generation. Returns (path, alternates) so callers can
    report that older copies exist.
    """
    target = f"{block}_manifest.json"
    found = []
    for dirpath, _dirnames, filenames in os.walk(frontend_root):
        if target in filenames:
            found.append(os.path.join(dirpath, target))
    if not found:
        return None, []
    found.sort(key=lambda p: (-os.path.getmtime(p), p))
    return found[0], found[1:]


def manifest_ports(path: str):
    with open(path) as f:
        man = json.load(f)
    ports = {}
    for group, plist in man.get("ports", {}).items():
        for p in plist:
            ports[p["name"]] = {"width": p["width"], "dir": p["dir"],
                                "group": group}
    return ports


def resolve(catalog_path=CATALOG, frontend_root=FRONTEND_ROOT,
            spec_path=SPEC_PATH) -> dict:
    with open(catalog_path) as f:
        catalog = json.load(f)
    with open(spec_path) as f:
        spec = json.load(f)

    errors = []
    schemas = {}
    for iface, idef in catalog["interfaces"].items():
        block = idef["block"]
        mpath, alternates = discover_manifest(frontend_root, block)
        if mpath is None:
            errors.append(f"{iface}: no manifest found for block {block!r} "
                          f"under {frontend_root}")
            continue
        ports = manifest_ports(mpath)

        kinds = {}
        for kind, fmap in idef["kinds"].items():
            fields = {}
            for fname, pname in fmap.items():
                if pname not in ports:
                    errors.append(
                        f"{iface}.{kind}.{fname}: port {pname!r} not in "
                        f"{block} manifest ({os.path.relpath(mpath, ROOT)}). "
                        f"The design changed — update interface_catalog.json.")
                    continue
                fields[fname] = {
                    "port": pname,
                    "width": ports[pname]["width"],
                    "dir": ports[pname]["dir"],
                }
            kinds[kind] = fields
        schemas[iface] = {
            "block": block,
            "manifest": os.path.relpath(mpath, ROOT),
            "description": idef.get("description", ""),
            "kinds": kinds,
        }

    if errors:
        raise SchemaError("schema resolution failed:\n  " + "\n  ".join(errors))

    return {
        "$comment": "GENERATED by schema_gen.py — do not edit. Regenerate "
                    "after any spec or RTL/manifest change.",
        "spec_source": spec.get("design_id", "unknown"),
        "spec_revision": spec.get("revision", "unknown"),
        "interfaces": schemas,
    }


def main() -> int:
    try:
        result = resolve()
    except SchemaError as e:
        print(f"ERROR: {e}")
        return 1

    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, "schemas.json")
    with open(out, "w") as f:
        json.dump(result, f, indent=2)

    print(f"spec: {result['spec_source']} rev {result['spec_revision']}")
    for iface, s in result["interfaces"].items():
        print(f"\n  {iface}  ({s['block']}, {s['manifest']})")
        for kind, fields in s["kinds"].items():
            fs = ", ".join(f"{n}[{d['width']}]" for n, d in fields.items())
            print(f"    {kind:10} {fs}")
    print(f"\nwrote {os.path.relpath(out, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
