#!/usr/bin/env python3
"""
rerun_scope.py — run one scope on Olympus through the TRANSACTION pipeline
===========================================================================
Replaces the legacy flow this tool used to drive. The old version simulated
`<scope>_tb.sv` + `<scope>_vectors.hex` — the cycle-exact expected-value
testbench generated by the pre-rebuild agent chain. On config_regs that path
reports 176 failures against RTL the transaction pipeline shows has 11, all
one already-filed spec gap: the legacy TB samples in the active region and
asserts pipeline-latency assumptions the spec never makes. Its verdicts are
evidence of nothing, in either direction.

This version runs the pipeline the rebuild exists for:

    sequence (given, or seeded constrained-random)
      -> driver_gen.py        deterministic stimulus driver (negedge driving)
      -> harness_gen.py       DUT + driver top, clock from the spec
      -> generated monitors   passive, bind-attached, post-NBA sampling
      -> xrun on Olympus      simulate; monitors emit TXN lines; no checking
      -> trace_extract.py     log -> observed .jsonl
      -> scoreboard.py        observed vs the gate-accepted predictor/checker

The testbench checks nothing on purpose. Judgment happens offline, against a
model that was graded by a spec-derived gate it never saw.

Usage:
    export OLYMPUS_PASSWORD=...        # or read from Validation/setup.env
    python3 Validation/tools/rerun_scope.py --scope config_regs
    python3 Validation/tools/rerun_scope.py --scope config_regs --seed 7
    python3 Validation/tools/rerun_scope.py --scope config_regs \
        --sequence Validation/sequences/generated/my_seq.json
"""

import argparse
import getpass
import glob
import json
import os
import subprocess
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "Validation", "agents"))

from sim_runner import CadenceSSHAgent

CCF = os.path.join(ROOT, "Validation", "coverage", "cov_conf.ccf")
CATALOG = os.path.join(ROOT, "Validation", "txn", "interface_catalog.json")
MON_DIR = os.path.join(ROOT, "Validation", "txn", "generated", "monitors")
SEQ_GEN = os.path.join(ROOT, "Validation", "sequences", "generated")
PREDICTORS = os.path.join(ROOT, "Validation", "predictors")


def load_password():
    pw = os.environ.get("OLYMPUS_PASSWORD")
    if pw:
        return pw
    env = os.path.join(ROOT, "Validation", "setup.env")
    if os.path.exists(env):
        for line in open(env):
            if line.strip().startswith("OLYMPUS_PASSWORD"):
                val = line.split("=", 1)[1].strip().strip('"').strip("'")
                if val:
                    print("(using OLYMPUS_PASSWORD from Validation/setup.env)")
                    return val
    return getpass.getpass("Olympus password: ")


def run_local(cmd):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True,
                       cwd=ROOT)
    return r.returncode, (r.stdout or "") + (r.stderr or "")


def find_rtl(scope):
    """The block's newest RTL under Frontend/ — no hand-kept table to
    fall out of date."""
    paths = sorted(glob.glob(os.path.join(ROOT, "Frontend", "**",
                                          f"{scope}.sv"), recursive=True),
                   key=lambda p: -os.path.getmtime(p))
    return paths[0] if paths else None


def scope_monitors(scope, catalog):
    """Monitor source files for every stream on this block, plus a bind file
    holding ONLY this block's bind lines — the full monitors_bind.sv names
    every module in the design, and xrun errors on a bind whose target was
    never compiled."""
    ifaces = sorted(i for i, d in catalog.items() if d.get("block") == scope)
    if not ifaces:
        raise SystemExit(f"no interface in the catalog belongs to block "
                         f"{scope!r} — nothing would be observed.")

    missing = [i for i in ifaces if not os.path.exists(
        os.path.join(MON_DIR, f"{i}_monitor.sv"))]
    if missing:
        print(f"  regenerating monitors ({', '.join(missing)} missing)...")
        rc, out = run_local("python3 Validation/txn/monitor_gen.py")
        still = [i for i in missing if not os.path.exists(
            os.path.join(MON_DIR, f"{i}_monitor.sv"))]
        if still:
            raise SystemExit(
                f"monitor_gen produced no monitor for {still} — these "
                f"streams cannot be observed, and an unobserved stream is "
                f"not a passing one.\n{out[-600:]}")

    full_bind = os.path.join(MON_DIR, "monitors_bind.sv")
    lines = [l for l in open(full_bind)
             if l.strip().startswith(f"bind {scope} ")]
    if not lines:
        raise SystemExit(f"monitors_bind.sv has no bind lines for module "
                         f"{scope!r}; regenerate monitors first.")
    bind_path = os.path.join(MON_DIR, f"{scope}_monitors_bind.sv")
    with open(bind_path, "w") as f:
        f.write(f"// GENERATED subset of monitors_bind.sv for a single-scope "
                f"run of {scope}.\n// The full file binds every block in the "
                f"design; xrun errors on binds\n// whose target module was "
                f"never compiled.\n\n" + "".join(lines))

    files = [os.path.join(MON_DIR, f"{i}_monitor.sv") for i in ifaces]
    return ifaces, files, bind_path


def pick_model(scope):
    for suffix in ("predictor", "checker"):
        p = os.path.join(PREDICTORS, f"{scope}_{suffix}.py")
        if os.path.exists(p):
            return p
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scope", required=True)
    ap.add_argument("--sequence", help="stimulus sequence .json; default is "
                                       "seeded constrained-random")
    ap.add_argument("--seed", type=int, default=1,
                    help="seed for the default random sequence")
    ap.add_argument("--drives", type=int, default=19,
                    help="drive count for the default random sequence")
    ap.add_argument("--no-coverage", action="store_true")
    ap.add_argument("--prep-only", action="store_true",
                    help="generate sequence, driver, harness and bind files, "
                         "then stop before connecting to Olympus")
    ap.add_argument("--timeout", type=int, default=600)
    args = ap.parse_args()
    scope = args.scope

    with open(CATALOG) as f:
        catalog = json.load(f)["interfaces"]

    rtl = find_rtl(scope)
    if not rtl:
        print(f"no {scope}.sv found under Frontend/ — nothing to validate.")
        return 1

    model = pick_model(scope)
    if not model:
        print(f"no accepted model for {scope!r} in Validation/predictors/ — "
              f"run predictor_agent.py first. Simulating without a model "
              f"would observe but never judge.")
        return 1

    # --- stimulus ----------------------------------------------------------
    seq_path = args.sequence
    if not seq_path:
        seq_path = os.path.join(SEQ_GEN, f"{scope}_rerun_seed{args.seed}.json")
        rc, out = run_local(
            f"python3 Validation/closure/random_sequence.py --scope {scope} "
            f"--seed {args.seed} --drives {args.drives} --out {seq_path}")
        if rc != 0:
            print(f"sequence generation failed:\n{out[-600:]}")
            return 1

    # Per-run work dir: two runs in flight used to overwrite each other's
    # shared seq_driver.sv between generation and upload.
    work = os.path.join(SEQ_GEN, "runs", scope)
    os.makedirs(work, exist_ok=True)
    rc, out = run_local(
        f"python3 Validation/sequences/driver_gen.py --sequence {seq_path} "
        f"--outdir {work}")
    if rc != 0:
        print(f"driver codegen rejected the sequence:\n{out[-600:]}")
        return 1
    rc, out = run_local(
        f"python3 Validation/sequences/harness_gen.py --scope {scope} "
        f"--sequence {seq_path} --outdir {work}")
    if rc != 0:
        print(f"harness generation failed:\n{out[-600:]}")
        return 1

    ifaces, mon_files, bind_path = scope_monitors(scope, catalog)
    driver = os.path.join(work, "seq_driver.sv")
    harness = os.path.join(work, f"{scope}_txn_harness.sv")

    print(f"Scope    : {scope}")
    print(f"RTL      : {os.path.relpath(rtl, ROOT)}")
    print(f"Sequence : {os.path.relpath(seq_path, ROOT)}")
    print(f"Model    : {os.path.relpath(model, ROOT)}")
    print(f"Monitors : {', '.join(ifaces)}")
    print(f"Coverage : {'off' if args.no_coverage else 'on (cov_conf.ccf)'}\n")

    if args.prep_only:
        print("  --prep-only: all local artifacts generated; skipping the "
              "cluster run.")
        for p in [rtl, driver, harness, bind_path] + mon_files:
            print(f"    {os.path.relpath(p, ROOT)}")
        return 0

    # --- simulate ----------------------------------------------------------
    agent = CadenceSSHAgent(work_subdir=f"runs/{scope}")
    try:
        agent.connect(password=load_password())
        print(f"Connected. Work dir: {agent.work_dir}")
        agent.clean_work_dir()

        gen = os.path.join(ROOT, "Validation", "sva", "generated")
        fcov_files = [os.path.join(gen, scope + sfx) for sfx in
                      ("_fcov.sv", "_fcov_bind.sv", "_coverage.sv",
                       "_coverage_bind.sv", "_sva.sv", "_sva_bind.sv")
                      if os.path.exists(os.path.join(gen, scope + sfx))]
        uploads = [rtl, driver, harness, bind_path] + mon_files + fcov_files
        agent.upload_files(uploads)

        cov = ""
        if not args.no_coverage:
            with open(CCF) as f:
                agent.write_remote_file("cov_conf.ccf", f.read())
            cov = (f"-coverage A -covoverwrite -covfile ./cov_conf.ccf "
                   f"-covtest {scope}_txn")

        names = " ".join(os.path.basename(p) for p in uploads)
        top = f"{scope}_txn_harness"
        cmd = (f"xrun -sv -access +rwc -timescale 1ns/1ps -clean {cov} "
               f"{names} -top {top} 2>&1")
        print(f"Running: {cmd}\n")
        res = agent.run_sim(cmd, timeout=args.timeout)
        stdout = res.get("stdout", "")
    except Exception as e:
        print(f"\nRUN FAILED: {e}")
        import traceback
        traceback.print_exc()
        return 2
    finally:
        agent.disconnect()

    # Beside reports/paths/: the legacy scopes/ tree (vector testbenches) is gone.
    rep_dir = os.path.join(ROOT, "Validation", "reports", "scopes", scope)
    os.makedirs(rep_dir, exist_ok=True)
    log_path = os.path.join(rep_dir, f"{scope}_txn_sim.log")
    with open(log_path, "w") as f:
        f.write(stdout)
        if res.get("stderr"):
            f.write("\n\n=== STDERR ===\n" + res["stderr"])
    print(f"  log -> {os.path.relpath(log_path, ROOT)}")

    lines = stdout.splitlines()
    evidence = [l for l in lines if "ASRTST" in l or "EILLVU" in l]
    errors = [l for l in lines
              if ("*E," in l or "*F," in l)
              and "ASRTST" not in l and "EILLVU" not in l]
    if errors:
        print("\n  COMPILE/ELABORATION ERRORS — no verdict is possible:")
        for e in errors[:10]:
            print(f"    {e[:160]}")
        return 2
    if evidence:
        print(f"\n  RUNTIME EVIDENCE: {len(evidence)} assertion failure(s) / "
              f"illegal coverage bin hit(s) — the design's own checks and "
              f"the spec-derived spacing bins disagree with its behaviour.")
    if "HARNESS_TIMEOUT" in stdout:
        print("\n  HARNESS TIMEOUT — the DUT or driver wedged; the trace "
              "below is partial and the verdict is not a pass/fail.")

    # --- extract and judge -------------------------------------------------
    observed = os.path.join(rep_dir, f"{scope}_txn_observed.jsonl")
    rc, out = run_local(
        f"python3 Validation/txn/trace_extract.py --log {log_path} "
        f"--out {observed} --summary")
    if rc != 0:
        print(f"trace extraction failed:\n{out[-600:]}")
        return 2
    print(out.strip())

    findings = os.path.join(rep_dir, f"{scope}_txn_findings.json")
    rc, out = run_local(
        f"python3 Validation/txn/scoreboard.py --scope {scope} "
        f"--trace {observed} --model {model} --findings {findings}")
    print("\n" + "=" * 62)
    print(out.strip())
    print("=" * 62)

    verdict = "pass" if rc == 0 else "fail"
    report = {
        "$schema": "validation-txn-run/1",
        "scope": scope,
        "pipeline": "transaction",
        "verdict": verdict,
        "timestamp": datetime.now().isoformat(),
        "rtl": os.path.relpath(rtl, ROOT),
        "sequence": os.path.relpath(seq_path, ROOT),
        "model": os.path.relpath(model, ROOT),
        "monitored_ifaces": ifaces,
        "coverage": not args.no_coverage,
        "log": os.path.relpath(log_path, ROOT),
        "observed_trace": os.path.relpath(observed, ROOT),
        "findings": os.path.relpath(findings, ROOT),
        "note": ("Verdict comes from the offline scoreboard against the "
                 "gate-accepted model; the testbench itself checks nothing. "
                 "This replaces the legacy vector-diff flow, whose 176 "
                 "config_regs 'failures' were artifacts of active-region "
                 "sampling and latency assumptions."),
    }
    with open(os.path.join(rep_dir, f"{scope}_txn_report.json"), "w") as f:
        json.dump(report, f, indent=2)
    print(f"\n  verdict : {verdict.upper()}")
    print(f"  report  -> Validation/reports/scopes/{scope}/{scope}_txn_report.json")
    return 0 if verdict == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
