// ddr3_controller — INTEGRATION SCAFFOLD, generated by integration/generate_top.py
//
// Wires ONLY the connections the frontend declared in the block manifests
// (50 nets). Every other port is exposed at the top level, so this builds
// end to end but is NOT a functionally complete memory controller.
// Blocks whose outputs nothing consumes yet: calibration, data_path
// Regenerate after the frontend backfills the `source` fields.

module ddr3_controller (
    input  logic clk,
    input  logic rst_n,
    input  logic [2:0]        bank_tracker_cmd_act_bank,
    input  logic [14:0]       bank_tracker_cmd_act_row,
    input  logic              bank_tracker_cmd_act_valid,
    input  logic              bank_tracker_cmd_pre_all,
    input  logic [2:0]        bank_tracker_cmd_pre_bank,
    input  logic              bank_tracker_cmd_pre_valid,
    input  logic [2:0]        bank_tracker_cmd_rd_bank,
    input  logic              bank_tracker_cmd_rd_valid,
    input  logic              bank_tracker_cmd_ref_valid,
    input  logic [2:0]        bank_tracker_cmd_wr_bank,
    input  logic              bank_tracker_cmd_wr_valid,
    input  logic              calibration_zqcs_ack,
    input  logic              cmd_queue_deq_grant,
    input  logic [3:0]        cmd_queue_deq_idx,
    input  logic [3:0]        cmd_queue_enq_aux,
    input  logic              cmd_queue_enq_valid,
    input  logic [7:0]        config_regs_csr_adr_i,
    input  logic              config_regs_csr_cyc_i,
    input  logic [31:0]       config_regs_csr_dat_i,
    input  logic [3:0]        config_regs_csr_sel_i,
    input  logic              config_regs_csr_stb_i,
    input  logic              config_regs_csr_we_i,
    input  logic              config_regs_sts_bist_done,
    input  logic              config_regs_sts_bist_fail,
    input  logic [12:0]       config_regs_sts_bist_fail_addr,
    input  logic              config_regs_sts_cal_done,
    input  logic              config_regs_sts_cal_fail,
    input  logic [15:0]       config_regs_sts_ecc_ce_count,
    input  logic              config_regs_sts_ecc_ue_event,
    input  logic              config_regs_sts_init_done,
    input  logic              config_regs_sts_init_fail_event,
    input  logic [2:0]        config_regs_sts_ref_pending_cnt,
    input  logic              config_regs_sts_ref_starve_event,
    input  logic              config_regs_sts_self_refresh_active,
    input  logic [31:0]       data_path_ddr_dq_i,
    input  logic              data_path_ddr_dqs_i,
    input  logic              init_fsm_enable,
    input  logic              refresh_ctrl_ref_ack,
    input  logic              wb_port_req_ready,
    input  logic [3:0]        wb_port_rsp_aux,
    input  logic [31:0]       wb_port_rsp_rdata,
    input  logic              wb_port_rsp_valid,
    input  logic [28:0]       wb_port_wb_adr_i,
    input  logic [1:0]        wb_port_wb_bte_i,
    input  logic [2:0]        wb_port_wb_cti_i,
    input  logic              wb_port_wb_cyc_i,
    input  logic [31:0]       wb_port_wb_dat_i,
    input  logic [3:0]        wb_port_wb_sel_i,
    input  logic              wb_port_wb_stb_i,
    input  logic              wb_port_wb_we_i,
    output logic [0:0]        addr_decoder_dec_rank,
    output logic              bank_tracker_all_banks_idle,
    output logic              bank_tracker_faw_allows_act,
    output logic              calibration_cal_done,
    output logic              calibration_cal_fail,
    output logic              calibration_zqcs_req,
    output logic [14:0]       cmd_gen_ddr_addr,
    output logic [2:0]        cmd_gen_ddr_bank,
    output logic              cmd_gen_ddr_cke,
    output logic [3:0]        cmd_gen_ddr_cmd,
    output logic              cmd_gen_ddr_odt,
    output logic              cmd_gen_ddr_reset_n,
    output logic [2:0]        cmd_gen_fb_act_bank,
    output logic [14:0]       cmd_gen_fb_act_row,
    output logic              cmd_gen_fb_act_valid,
    output logic              cmd_gen_fb_pre_valid,
    output logic              cmd_gen_fb_ref_valid,
    output logic              cmd_queue_enq_ready,
    output logic [4:0]        cmd_queue_queue_count,
    output logic              cmd_queue_queue_empty,
    output logic              cmd_queue_queue_full,
    output logic [28:0]       config_regs_cfg_bist_addr_end,
    output logic              config_regs_cfg_bist_addr_mode,
    output logic [28:0]       config_regs_cfg_bist_addr_start,
    output logic [2:0]        config_regs_cfg_bist_pattern,
    output logic              config_regs_cfg_bist_start,
    output logic              config_regs_cfg_ecc_enable,
    output logic              config_regs_cfg_force_self_ref,
    output logic              config_regs_cfg_row_policy,
    output logic              config_regs_cfg_sched_policy,
    output logic [1:0]        config_regs_cfg_self_ref_mode,
    output logic              config_regs_csr_ack_o,
    output logic [31:0]       config_regs_csr_dat_o,
    output logic              config_regs_csr_err_o,
    output logic [3:0]        data_path_ddr_dm_o,
    output logic [31:0]       data_path_ddr_dq_o,
    output logic              data_path_ddr_dq_oe,
    output logic              data_path_ddr_dqs_o,
    output logic              data_path_ddr_dqs_oe,
    output logic [3:0]        data_path_rd_rsp_aux,
    output logic [31:0]       data_path_rd_rsp_data,
    output logic              data_path_rd_rsp_valid,
    output logic              data_path_wr_data_ready,
    output logic [14:0]       init_fsm_init_addr,
    output logic [2:0]        init_fsm_init_bank,
    output logic              init_fsm_init_cke,
    output logic [3:0]        init_fsm_init_cmd,
    output logic              init_fsm_init_cmd_valid,
    output logic              init_fsm_init_fail,
    output logic              init_fsm_init_reset_n,
    output logic [3:0]        init_fsm_init_state,
    output logic [2:0]        refresh_ctrl_ref_pending_cnt,
    output logic              refresh_ctrl_ref_starve_flag,
    output logic              scheduler_deq_grant,
    output logic [3:0]        scheduler_deq_idx,
    output logic              scheduler_ref_ack,
    output logic [3:0]        wb_port_req_aux,
    output logic              wb_port_wb_ack_o,
    output logic [31:0]       wb_port_wb_dat_o,
    output logic              wb_port_wb_err_o,
    output logic              wb_port_wb_stall_o
);

    // ── internal nets (declared block-to-block connections) ──
    logic [2:0]        w_addr_decoder__dec_bank;
    logic [9:0]        w_addr_decoder__dec_col;
    logic [14:0]       w_addr_decoder__dec_row;
    logic [7:0]        w_bank_tracker__bank_act_allowed;
    logic [7:0]        w_bank_tracker__bank_is_active;
    logic [14:0]       w_bank_tracker__bank_open_row[8];
    logic [7:0]        w_bank_tracker__bank_pre_allowed;
    logic [7:0]        w_bank_tracker__bank_rd_allowed;
    logic [7:0]        w_bank_tracker__bank_wr_allowed;
    logic              w_cmd_gen__fb_rd_valid;
    logic              w_cmd_gen__fb_wr_valid;
    logic [3:0]        w_cmd_queue__entry_aux[16];
    logic [2:0]        w_cmd_queue__entry_bank[16];
    logic [9:0]        w_cmd_queue__entry_col[16];
    logic [14:0]       w_cmd_queue__entry_row[16];
    logic [15:0]       w_cmd_queue__entry_valid;
    logic              w_cmd_queue__entry_we[16];
    logic [7:0]        w_config_regs__cfg_CL_nCK;
    logic [7:0]        w_config_regs__cfg_CWL_nCK;
    logic              w_config_regs__cfg_force_refresh;
    logic [3:0]        w_config_regs__cfg_max_postpone;
    logic              w_config_regs__cfg_ref_priority;
    logic [7:0]        w_config_regs__cfg_tCCD_nCK;
    logic [7:0]        w_config_regs__cfg_tFAW_nCK;
    logic [7:0]        w_config_regs__cfg_tRAS_nCK;
    logic [7:0]        w_config_regs__cfg_tRCD_nCK;
    logic [7:0]        w_config_regs__cfg_tRC_nCK;
    logic [23:0]       w_config_regs__cfg_tREFI_nCK;
    logic [7:0]        w_config_regs__cfg_tRFC_nCK;
    logic [7:0]        w_config_regs__cfg_tRP_nCK;
    logic [7:0]        w_config_regs__cfg_tRRD_nCK;
    logic [7:0]        w_config_regs__cfg_tRTP_nCK;
    logic [7:0]        w_config_regs__cfg_tWR_nCK;
    logic [7:0]        w_config_regs__cfg_tWTR_nCK;
    logic [3:0]        w_config_regs__cfg_urgent_threshold;
    logic              w_init_fsm__init_done;
    logic              w_refresh_ctrl__ref_required;
    logic              w_refresh_ctrl__ref_urgent;
    logic [3:0]        w_scheduler__cmd_aux;
    logic [2:0]        w_scheduler__cmd_bank;
    logic [9:0]        w_scheduler__cmd_col;
    logic [14:0]       w_scheduler__cmd_row;
    logic [3:0]        w_scheduler__cmd_type;
    logic              w_scheduler__cmd_valid;
    logic              w_scheduler__cmd_we;
    logic [28:0]       w_wb_port__req_addr;
    logic              w_wb_port__req_valid;
    logic [31:0]       w_wb_port__req_wdata;
    logic              w_wb_port__req_we;
    logic [3:0]        w_wb_port__req_wmask;

    addr_decoder u_addr_decoder (
        .dec_bank(w_addr_decoder__dec_bank),
        .dec_col(w_addr_decoder__dec_col),
        .dec_rank(addr_decoder_dec_rank),
        .dec_row(w_addr_decoder__dec_row),
        .req_addr(w_wb_port__req_addr)
    );

    bank_tracker u_bank_tracker (
        .clk(clk),
        .rst_n(rst_n),
        .all_banks_idle(bank_tracker_all_banks_idle),
        .bank_act_allowed(w_bank_tracker__bank_act_allowed),
        .bank_is_active(w_bank_tracker__bank_is_active),
        .bank_open_row(w_bank_tracker__bank_open_row),
        .bank_pre_allowed(w_bank_tracker__bank_pre_allowed),
        .bank_rd_allowed(w_bank_tracker__bank_rd_allowed),
        .bank_wr_allowed(w_bank_tracker__bank_wr_allowed),
        .cfg_tCCD_nCK(w_config_regs__cfg_tCCD_nCK),
        .cfg_tFAW_nCK(w_config_regs__cfg_tFAW_nCK),
        .cfg_tRAS_nCK(w_config_regs__cfg_tRAS_nCK),
        .cfg_tRCD_nCK(w_config_regs__cfg_tRCD_nCK),
        .cfg_tRC_nCK(w_config_regs__cfg_tRC_nCK),
        .cfg_tRFC_nCK(w_config_regs__cfg_tRFC_nCK),
        .cfg_tRP_nCK(w_config_regs__cfg_tRP_nCK),
        .cfg_tRRD_nCK(w_config_regs__cfg_tRRD_nCK),
        .cfg_tRTP_nCK(w_config_regs__cfg_tRTP_nCK),
        .cfg_tWR_nCK(w_config_regs__cfg_tWR_nCK),
        .cfg_tWTR_nCK(w_config_regs__cfg_tWTR_nCK),
        .cmd_act_bank(bank_tracker_cmd_act_bank),
        .cmd_act_row(bank_tracker_cmd_act_row),
        .cmd_act_valid(bank_tracker_cmd_act_valid),
        .cmd_pre_all(bank_tracker_cmd_pre_all),
        .cmd_pre_bank(bank_tracker_cmd_pre_bank),
        .cmd_pre_valid(bank_tracker_cmd_pre_valid),
        .cmd_rd_bank(bank_tracker_cmd_rd_bank),
        .cmd_rd_valid(bank_tracker_cmd_rd_valid),
        .cmd_ref_valid(bank_tracker_cmd_ref_valid),
        .cmd_wr_bank(bank_tracker_cmd_wr_bank),
        .cmd_wr_valid(bank_tracker_cmd_wr_valid),
        .faw_allows_act(bank_tracker_faw_allows_act)
    );

    calibration u_calibration (
        .clk(clk),
        .rst_n(rst_n),
        .cal_done(calibration_cal_done),
        .cal_fail(calibration_cal_fail),
        .init_done(w_init_fsm__init_done),
        .zqcs_ack(calibration_zqcs_ack),
        .zqcs_req(calibration_zqcs_req)
    );

    cmd_gen u_cmd_gen (
        .clk(clk),
        .rst_n(rst_n),
        .ddr_addr(cmd_gen_ddr_addr),
        .ddr_bank(cmd_gen_ddr_bank),
        .ddr_cke(cmd_gen_ddr_cke),
        .ddr_cmd(cmd_gen_ddr_cmd),
        .ddr_odt(cmd_gen_ddr_odt),
        .ddr_reset_n(cmd_gen_ddr_reset_n),
        .fb_act_bank(cmd_gen_fb_act_bank),
        .fb_act_row(cmd_gen_fb_act_row),
        .fb_act_valid(cmd_gen_fb_act_valid),
        .fb_pre_valid(cmd_gen_fb_pre_valid),
        .fb_rd_valid(w_cmd_gen__fb_rd_valid),
        .fb_ref_valid(cmd_gen_fb_ref_valid),
        .fb_wr_valid(w_cmd_gen__fb_wr_valid),
        .sched_aux(w_scheduler__cmd_aux),
        .sched_bank(w_scheduler__cmd_bank),
        .sched_col(w_scheduler__cmd_col),
        .sched_row(w_scheduler__cmd_row),
        .sched_type(w_scheduler__cmd_type),
        .sched_valid(w_scheduler__cmd_valid),
        .sched_we(w_scheduler__cmd_we)
    );

    cmd_queue u_cmd_queue (
        .clk(clk),
        .rst_n(rst_n),
        .deq_grant(cmd_queue_deq_grant),
        .deq_idx(cmd_queue_deq_idx),
        .enq_aux(cmd_queue_enq_aux),
        .enq_bank(w_addr_decoder__dec_bank),
        .enq_col(w_addr_decoder__dec_col),
        .enq_ready(cmd_queue_enq_ready),
        .enq_row(w_addr_decoder__dec_row),
        .enq_valid(cmd_queue_enq_valid),
        .enq_we(w_wb_port__req_we),
        .entry_aux(w_cmd_queue__entry_aux),
        .entry_bank(w_cmd_queue__entry_bank),
        .entry_col(w_cmd_queue__entry_col),
        .entry_row(w_cmd_queue__entry_row),
        .entry_valid(w_cmd_queue__entry_valid),
        .entry_we(w_cmd_queue__entry_we),
        .queue_count(cmd_queue_queue_count),
        .queue_empty(cmd_queue_queue_empty),
        .queue_full(cmd_queue_queue_full)
    );

    config_regs u_config_regs (
        .clk(clk),
        .rst_n(rst_n),
        .cfg_CL_nCK(w_config_regs__cfg_CL_nCK),
        .cfg_CWL_nCK(w_config_regs__cfg_CWL_nCK),
        .cfg_bist_addr_end(config_regs_cfg_bist_addr_end),
        .cfg_bist_addr_mode(config_regs_cfg_bist_addr_mode),
        .cfg_bist_addr_start(config_regs_cfg_bist_addr_start),
        .cfg_bist_pattern(config_regs_cfg_bist_pattern),
        .cfg_bist_start(config_regs_cfg_bist_start),
        .cfg_ecc_enable(config_regs_cfg_ecc_enable),
        .cfg_force_refresh(w_config_regs__cfg_force_refresh),
        .cfg_force_self_ref(config_regs_cfg_force_self_ref),
        .cfg_max_postpone(w_config_regs__cfg_max_postpone),
        .cfg_ref_priority(w_config_regs__cfg_ref_priority),
        .cfg_row_policy(config_regs_cfg_row_policy),
        .cfg_sched_policy(config_regs_cfg_sched_policy),
        .cfg_self_ref_mode(config_regs_cfg_self_ref_mode),
        .cfg_tCCD_nCK(w_config_regs__cfg_tCCD_nCK),
        .cfg_tFAW_nCK(w_config_regs__cfg_tFAW_nCK),
        .cfg_tRAS_nCK(w_config_regs__cfg_tRAS_nCK),
        .cfg_tRCD_nCK(w_config_regs__cfg_tRCD_nCK),
        .cfg_tRC_nCK(w_config_regs__cfg_tRC_nCK),
        .cfg_tREFI_nCK(w_config_regs__cfg_tREFI_nCK),
        .cfg_tRFC_nCK(w_config_regs__cfg_tRFC_nCK),
        .cfg_tRP_nCK(w_config_regs__cfg_tRP_nCK),
        .cfg_tRRD_nCK(w_config_regs__cfg_tRRD_nCK),
        .cfg_tRTP_nCK(w_config_regs__cfg_tRTP_nCK),
        .cfg_tWR_nCK(w_config_regs__cfg_tWR_nCK),
        .cfg_tWTR_nCK(w_config_regs__cfg_tWTR_nCK),
        .cfg_urgent_threshold(w_config_regs__cfg_urgent_threshold),
        .csr_ack_o(config_regs_csr_ack_o),
        .csr_adr_i(config_regs_csr_adr_i),
        .csr_cyc_i(config_regs_csr_cyc_i),
        .csr_dat_i(config_regs_csr_dat_i),
        .csr_dat_o(config_regs_csr_dat_o),
        .csr_err_o(config_regs_csr_err_o),
        .csr_sel_i(config_regs_csr_sel_i),
        .csr_stb_i(config_regs_csr_stb_i),
        .csr_we_i(config_regs_csr_we_i),
        .sts_bist_done(config_regs_sts_bist_done),
        .sts_bist_fail(config_regs_sts_bist_fail),
        .sts_bist_fail_addr(config_regs_sts_bist_fail_addr),
        .sts_cal_done(config_regs_sts_cal_done),
        .sts_cal_fail(config_regs_sts_cal_fail),
        .sts_ecc_ce_count(config_regs_sts_ecc_ce_count),
        .sts_ecc_ue_event(config_regs_sts_ecc_ue_event),
        .sts_init_done(config_regs_sts_init_done),
        .sts_init_fail_event(config_regs_sts_init_fail_event),
        .sts_ref_pending_cnt(config_regs_sts_ref_pending_cnt),
        .sts_ref_starve_event(config_regs_sts_ref_starve_event),
        .sts_self_refresh_active(config_regs_sts_self_refresh_active)
    );

    data_path u_data_path (
        .clk(clk),
        .rst_n(rst_n),
        .cfg_CL_nCK(w_config_regs__cfg_CL_nCK),
        .cfg_CWL_nCK(w_config_regs__cfg_CWL_nCK),
        .cmd_aux(w_scheduler__cmd_aux),
        .cmd_rd_valid(w_cmd_gen__fb_rd_valid),
        .cmd_wr_valid(w_cmd_gen__fb_wr_valid),
        .ddr_dm_o(data_path_ddr_dm_o),
        .ddr_dq_i(data_path_ddr_dq_i),
        .ddr_dq_o(data_path_ddr_dq_o),
        .ddr_dq_oe(data_path_ddr_dq_oe),
        .ddr_dqs_i(data_path_ddr_dqs_i),
        .ddr_dqs_o(data_path_ddr_dqs_o),
        .ddr_dqs_oe(data_path_ddr_dqs_oe),
        .rd_rsp_aux(data_path_rd_rsp_aux),
        .rd_rsp_data(data_path_rd_rsp_data),
        .rd_rsp_valid(data_path_rd_rsp_valid),
        .wr_data(w_wb_port__req_wdata),
        .wr_data_ready(data_path_wr_data_ready),
        .wr_data_valid(w_wb_port__req_valid),
        .wr_mask(w_wb_port__req_wmask)
    );

    init_fsm u_init_fsm (
        .clk(clk),
        .rst_n(rst_n),
        .enable(init_fsm_enable),
        .init_addr(init_fsm_init_addr),
        .init_bank(init_fsm_init_bank),
        .init_cke(init_fsm_init_cke),
        .init_cmd(init_fsm_init_cmd),
        .init_cmd_valid(init_fsm_init_cmd_valid),
        .init_done(w_init_fsm__init_done),
        .init_fail(init_fsm_init_fail),
        .init_reset_n(init_fsm_init_reset_n),
        .init_state(init_fsm_init_state)
    );

    refresh_ctrl u_refresh_ctrl (
        .clk(clk),
        .rst_n(rst_n),
        .cfg_force_refresh(w_config_regs__cfg_force_refresh),
        .cfg_max_postpone(w_config_regs__cfg_max_postpone),
        .cfg_ref_priority(w_config_regs__cfg_ref_priority),
        .cfg_tREFI_nCK(w_config_regs__cfg_tREFI_nCK),
        .cfg_urgent_threshold(w_config_regs__cfg_urgent_threshold),
        .init_done(w_init_fsm__init_done),
        .ref_ack(refresh_ctrl_ref_ack),
        .ref_pending_cnt(refresh_ctrl_ref_pending_cnt),
        .ref_required(w_refresh_ctrl__ref_required),
        .ref_starve_flag(refresh_ctrl_ref_starve_flag),
        .ref_urgent(w_refresh_ctrl__ref_urgent)
    );

    scheduler u_scheduler (
        .clk(clk),
        .rst_n(rst_n),
        .bank_act_allowed(w_bank_tracker__bank_act_allowed),
        .bank_is_active(w_bank_tracker__bank_is_active),
        .bank_open_row(w_bank_tracker__bank_open_row),
        .bank_pre_allowed(w_bank_tracker__bank_pre_allowed),
        .bank_rd_allowed(w_bank_tracker__bank_rd_allowed),
        .bank_wr_allowed(w_bank_tracker__bank_wr_allowed),
        .cmd_aux(w_scheduler__cmd_aux),
        .cmd_bank(w_scheduler__cmd_bank),
        .cmd_col(w_scheduler__cmd_col),
        .cmd_row(w_scheduler__cmd_row),
        .cmd_type(w_scheduler__cmd_type),
        .cmd_valid(w_scheduler__cmd_valid),
        .cmd_we(w_scheduler__cmd_we),
        .deq_grant(scheduler_deq_grant),
        .deq_idx(scheduler_deq_idx),
        .q_aux(w_cmd_queue__entry_aux),
        .q_bank(w_cmd_queue__entry_bank),
        .q_col(w_cmd_queue__entry_col),
        .q_row(w_cmd_queue__entry_row),
        .q_valid(w_cmd_queue__entry_valid),
        .q_we(w_cmd_queue__entry_we),
        .ref_ack(scheduler_ref_ack),
        .ref_required(w_refresh_ctrl__ref_required),
        .ref_urgent(w_refresh_ctrl__ref_urgent)
    );

    wb_port u_wb_port (
        .clk(clk),
        .rst_n(rst_n),
        .req_addr(w_wb_port__req_addr),
        .req_aux(wb_port_req_aux),
        .req_ready(wb_port_req_ready),
        .req_valid(w_wb_port__req_valid),
        .req_wdata(w_wb_port__req_wdata),
        .req_we(w_wb_port__req_we),
        .req_wmask(w_wb_port__req_wmask),
        .rsp_aux(wb_port_rsp_aux),
        .rsp_rdata(wb_port_rsp_rdata),
        .rsp_valid(wb_port_rsp_valid),
        .wb_ack_o(wb_port_wb_ack_o),
        .wb_adr_i(wb_port_wb_adr_i),
        .wb_bte_i(wb_port_wb_bte_i),
        .wb_cti_i(wb_port_wb_cti_i),
        .wb_cyc_i(wb_port_wb_cyc_i),
        .wb_dat_i(wb_port_wb_dat_i),
        .wb_dat_o(wb_port_wb_dat_o),
        .wb_err_o(wb_port_wb_err_o),
        .wb_sel_i(wb_port_wb_sel_i),
        .wb_stall_o(wb_port_wb_stall_o),
        .wb_stb_i(wb_port_wb_stb_i),
        .wb_we_i(wb_port_wb_we_i)
    );

endmodule
