// GENERATED by Validation/structural/chain_harness_gen.py --formal — DO NOT EDIT.
//
// Path     : path_01_write_cmd
// Blocks   : addr_decoder, bank_tracker, cmd_gen, cmd_queue, config_regs, data_path, refresh_ctrl, scheduler, wb_port
//
// Formal top for JasperGold: the path's blocks wired per integration_map.json,
// host inputs and DRAM data left free, CSR/status inputs tied as in simulation.
// The generated SVA attach through their bind files; nothing here checks anything.

module chain_formal (
    input logic clk,
    input logic rst_n,
    input logic [15:0] stub__u_dram__ddr_dq_i,
    input logic stub__u_dram__ddr_dqs_i,
    input logic free__wb_port__wb_cyc_i,
    input logic free__wb_port__wb_stb_i,
    input logic free__wb_port__wb_we_i,
    input logic [28:0] free__wb_port__wb_adr_i,
    input logic [31:0] free__wb_port__wb_dat_i,
    input logic [3:0] free__wb_port__wb_sel_i,
    input logic [1:0] free__wb_port__wb_bte_i,
    input logic [2:0] free__wb_port__wb_cti_i
);

  logic [28:0] wb_port__req_addr;
  logic [14:0] addr_decoder__dec_row;
  logic [2:0] addr_decoder__dec_bank;
  logic [9:0] addr_decoder__dec_col;
  logic addr_decoder__dec_rank;
  logic cmd_gen__fb_act_valid;
  logic [2:0] cmd_gen__fb_act_bank;
  logic [14:0] cmd_gen__fb_act_row;
  logic cmd_gen__fb_pre_valid;
  logic [2:0] cmd_gen__fb_pre_bank;
  logic cmd_gen__fb_pre_all;
  logic cmd_gen__fb_rd_valid;
  logic [2:0] cmd_gen__fb_rd_bank;
  logic cmd_gen__fb_wr_valid;
  logic [2:0] cmd_gen__fb_wr_bank;
  logic cmd_gen__fb_ref_valid;
  logic [7:0] config_regs__cfg_tRCD_nCK;
  logic [7:0] config_regs__cfg_tRP_nCK;
  logic [7:0] config_regs__cfg_tRAS_nCK;
  logic [7:0] config_regs__cfg_tRC_nCK;
  logic [7:0] config_regs__cfg_tRRD_nCK;
  logic [7:0] config_regs__cfg_tFAW_nCK;
  logic [7:0] config_regs__cfg_tWTR_nCK;
  logic [7:0] config_regs__cfg_tWR_nCK;
  logic [7:0] config_regs__cfg_tRTP_nCK;
  logic [7:0] config_regs__cfg_tCCD_nCK;
  logic [7:0] config_regs__cfg_tRFC_nCK;
  logic [7:0] bank_tracker__bank_is_active;
  logic [14:0] bank_tracker__bank_open_row [8];
  logic [7:0] bank_tracker__bank_act_allowed;
  logic [7:0] bank_tracker__bank_rd_allowed;
  logic [7:0] bank_tracker__bank_wr_allowed;
  logic [7:0] bank_tracker__bank_pre_allowed;
  logic bank_tracker__all_banks_idle;
  logic bank_tracker__faw_allows_act;
  logic scheduler__cmd_valid;
  logic [3:0] scheduler__cmd_type;
  logic [14:0] scheduler__cmd_row;
  logic [9:0] scheduler__cmd_col;
  logic [2:0] scheduler__cmd_bank;
  logic scheduler__cmd_we;
  logic [3:0] scheduler__cmd_aux;
  logic [3:0] cmd_gen__ddr_cmd;
  logic [14:0] cmd_gen__ddr_addr;
  logic [2:0] cmd_gen__ddr_bank;
  logic cmd_gen__ddr_cke;
  logic cmd_gen__ddr_reset_n;
  logic cmd_gen__ddr_odt;
  logic cmd_gen__cmd_out_valid;
  logic cmd_gen__cmd_out_we;
  logic [3:0] cmd_gen__cmd_out_aux;
  logic wb_port__req_valid;
  logic cmd_queue__enq_ready;
  logic wb_port__req_we;
  logic [3:0] wb_port__req_aux;
  logic scheduler__deq_grant;
  logic [3:0] scheduler__deq_idx;
  logic [15:0] cmd_queue__entry_valid;
  logic [14:0] cmd_queue__entry_row [16];
  logic [9:0] cmd_queue__entry_col [16];
  logic [2:0] cmd_queue__entry_bank [16];
  logic [0:0] cmd_queue__entry_we [16];
  logic [3:0] cmd_queue__entry_aux [16];
  logic cmd_queue__queue_full;
  logic cmd_queue__queue_empty;
  logic [4:0] cmd_queue__queue_count;
  logic tie__config_regs__csr_cyc_i;
  logic tie__config_regs__csr_stb_i;
  logic tie__config_regs__csr_we_i;
  logic [7:0] tie__config_regs__csr_adr_i;
  logic [31:0] tie__config_regs__csr_dat_i;
  logic [3:0] tie__config_regs__csr_sel_i;
  logic config_regs__csr_ack_o;
  logic [31:0] config_regs__csr_dat_o;
  logic config_regs__csr_err_o;
  logic tie__config_regs__sts_init_done;
  logic tie__config_regs__sts_cal_done;
  logic tie__config_regs__sts_cal_fail;
  logic tie__config_regs__sts_bist_done;
  logic tie__config_regs__sts_bist_fail;
  logic [3:0] refresh_ctrl__ref_pending_cnt;
  logic tie__config_regs__sts_self_refresh_active;
  logic [15:0] tie__config_regs__sts_ecc_ce_count;
  logic tie__config_regs__sts_ecc_ue_event;
  logic refresh_ctrl__ref_starve_flag;
  logic tie__config_regs__sts_init_fail_event;
  logic [12:0] tie__config_regs__sts_bist_fail_addr;
  logic [7:0] config_regs__cfg_CL_nCK;
  logic [7:0] config_regs__cfg_CWL_nCK;
  logic [23:0] config_regs__cfg_tREFI_nCK;
  logic config_regs__cfg_sched_policy;
  logic config_regs__cfg_row_policy;
  logic [1:0] config_regs__cfg_self_ref_mode;
  logic config_regs__cfg_ecc_enable;
  logic config_regs__cfg_bist_start;
  logic config_regs__cfg_force_refresh;
  logic config_regs__cfg_force_self_ref;
  logic [3:0] config_regs__cfg_max_postpone;
  logic [3:0] config_regs__cfg_urgent_threshold;
  logic config_regs__cfg_ref_priority;
  logic [2:0] config_regs__cfg_bist_pattern;
  logic config_regs__cfg_bist_addr_mode;
  logic [28:0] config_regs__cfg_bist_addr_start;
  logic [28:0] config_regs__cfg_bist_addr_end;
  logic xg__data_path__wr_data_valid;
  logic [31:0] wb_port__req_wdata;
  logic [3:0] wb_port__req_wmask;
  logic data_path__wr_data_ready;
  logic data_path__rd_rsp_valid;
  logic [31:0] data_path__rd_rsp_data;
  logic [3:0] data_path__rd_rsp_aux;
  logic [15:0] data_path__ddr_dq_o;
  logic data_path__ddr_dq_oe;
  logic [1:0] data_path__ddr_dm_o;
  logic data_path__ddr_dqs_o;
  logic data_path__ddr_dqs_oe;
  logic tie__refresh_ctrl__init_done;
  logic refresh_ctrl__ref_required;
  logic refresh_ctrl__ref_urgent;
  logic scheduler__ref_ack;
  logic wb_port__wb_ack_o;
  logic [31:0] wb_port__wb_dat_o;
  logic wb_port__wb_stall_o;
  logic wb_port__wb_err_o;

  assign tie__config_regs__csr_cyc_i = '0;
  assign tie__config_regs__csr_stb_i = '0;
  assign tie__config_regs__csr_we_i = '0;
  assign tie__config_regs__csr_adr_i = '0;
  assign tie__config_regs__csr_dat_i = '0;
  assign tie__config_regs__csr_sel_i = '0;
  assign tie__config_regs__sts_init_done = '0;
  assign tie__config_regs__sts_cal_done = '0;
  assign tie__config_regs__sts_cal_fail = '0;
  assign tie__config_regs__sts_bist_done = '0;
  assign tie__config_regs__sts_bist_fail = '0;
  assign tie__config_regs__sts_self_refresh_active = '0;
  assign tie__config_regs__sts_ecc_ce_count = '0;
  assign tie__config_regs__sts_ecc_ue_event = '0;
  assign tie__config_regs__sts_init_fail_event = '0;
  assign tie__config_regs__sts_bist_fail_addr = '0;
  assign xg__data_path__wr_data_valid = wb_port__req_valid && wb_port__req_we && cmd_queue__enq_ready;   // expr glue
  assign tie__refresh_ctrl__init_done = 1'b1;



  addr_decoder u_addr_decoder (
    .req_addr(wb_port__req_addr),
    .dec_row(addr_decoder__dec_row),
    .dec_bank(addr_decoder__dec_bank),
    .dec_col(addr_decoder__dec_col),
    .dec_rank(addr_decoder__dec_rank)
  );
  bank_tracker u_bank_tracker (
    .clk(clk),
    .rst_n(rst_n),
    .cmd_act_valid(cmd_gen__fb_act_valid),
    .cmd_act_bank(cmd_gen__fb_act_bank),
    .cmd_act_row(cmd_gen__fb_act_row),
    .cmd_pre_valid(cmd_gen__fb_pre_valid),
    .cmd_pre_bank(cmd_gen__fb_pre_bank),
    .cmd_pre_all(cmd_gen__fb_pre_all),
    .cmd_rd_valid(cmd_gen__fb_rd_valid),
    .cmd_rd_bank(cmd_gen__fb_rd_bank),
    .cmd_wr_valid(cmd_gen__fb_wr_valid),
    .cmd_wr_bank(cmd_gen__fb_wr_bank),
    .cmd_ref_valid(cmd_gen__fb_ref_valid),
    .cfg_tRCD_nCK(config_regs__cfg_tRCD_nCK),
    .cfg_tRP_nCK(config_regs__cfg_tRP_nCK),
    .cfg_tRAS_nCK(config_regs__cfg_tRAS_nCK),
    .cfg_tRC_nCK(config_regs__cfg_tRC_nCK),
    .cfg_tRRD_nCK(config_regs__cfg_tRRD_nCK),
    .cfg_tFAW_nCK(config_regs__cfg_tFAW_nCK),
    .cfg_tWTR_nCK(config_regs__cfg_tWTR_nCK),
    .cfg_tWR_nCK(config_regs__cfg_tWR_nCK),
    .cfg_tRTP_nCK(config_regs__cfg_tRTP_nCK),
    .cfg_tCCD_nCK(config_regs__cfg_tCCD_nCK),
    .cfg_tRFC_nCK(config_regs__cfg_tRFC_nCK),
    .bank_is_active(bank_tracker__bank_is_active),
    .bank_open_row(bank_tracker__bank_open_row),
    .bank_act_allowed(bank_tracker__bank_act_allowed),
    .bank_rd_allowed(bank_tracker__bank_rd_allowed),
    .bank_wr_allowed(bank_tracker__bank_wr_allowed),
    .bank_pre_allowed(bank_tracker__bank_pre_allowed),
    .all_banks_idle(bank_tracker__all_banks_idle),
    .faw_allows_act(bank_tracker__faw_allows_act)
  );
  cmd_gen u_cmd_gen (
    .clk(clk),
    .rst_n(rst_n),
    .sched_valid(scheduler__cmd_valid),
    .sched_type(scheduler__cmd_type),
    .sched_row(scheduler__cmd_row),
    .sched_col(scheduler__cmd_col),
    .sched_bank(scheduler__cmd_bank),
    .sched_we(scheduler__cmd_we),
    .sched_aux(scheduler__cmd_aux),
    .ddr_cmd(cmd_gen__ddr_cmd),
    .ddr_addr(cmd_gen__ddr_addr),
    .ddr_bank(cmd_gen__ddr_bank),
    .ddr_cke(cmd_gen__ddr_cke),
    .ddr_reset_n(cmd_gen__ddr_reset_n),
    .ddr_odt(cmd_gen__ddr_odt),
    .fb_act_valid(cmd_gen__fb_act_valid),
    .fb_act_bank(cmd_gen__fb_act_bank),
    .fb_act_row(cmd_gen__fb_act_row),
    .fb_pre_valid(cmd_gen__fb_pre_valid),
    .fb_pre_bank(cmd_gen__fb_pre_bank),
    .fb_pre_all(cmd_gen__fb_pre_all),
    .fb_rd_valid(cmd_gen__fb_rd_valid),
    .fb_rd_bank(cmd_gen__fb_rd_bank),
    .fb_wr_valid(cmd_gen__fb_wr_valid),
    .fb_wr_bank(cmd_gen__fb_wr_bank),
    .fb_ref_valid(cmd_gen__fb_ref_valid),
    .cmd_out_valid(cmd_gen__cmd_out_valid),
    .cmd_out_we(cmd_gen__cmd_out_we),
    .cmd_out_aux(cmd_gen__cmd_out_aux)
  );
  cmd_queue u_cmd_queue (
    .clk(clk),
    .rst_n(rst_n),
    .enq_valid(wb_port__req_valid),
    .enq_ready(cmd_queue__enq_ready),
    .enq_row(addr_decoder__dec_row),
    .enq_col(addr_decoder__dec_col),
    .enq_bank(addr_decoder__dec_bank),
    .enq_we(wb_port__req_we),
    .enq_aux(wb_port__req_aux),
    .deq_grant(scheduler__deq_grant),
    .deq_idx(scheduler__deq_idx),
    .entry_valid(cmd_queue__entry_valid),
    .entry_row(cmd_queue__entry_row),
    .entry_col(cmd_queue__entry_col),
    .entry_bank(cmd_queue__entry_bank),
    .entry_we(cmd_queue__entry_we),
    .entry_aux(cmd_queue__entry_aux),
    .queue_full(cmd_queue__queue_full),
    .queue_empty(cmd_queue__queue_empty),
    .queue_count(cmd_queue__queue_count)
  );
  config_regs u_config_regs (
    .clk(clk),
    .rst_n(rst_n),
    .csr_cyc_i(tie__config_regs__csr_cyc_i),
    .csr_stb_i(tie__config_regs__csr_stb_i),
    .csr_we_i(tie__config_regs__csr_we_i),
    .csr_adr_i(tie__config_regs__csr_adr_i),
    .csr_dat_i(tie__config_regs__csr_dat_i),
    .csr_sel_i(tie__config_regs__csr_sel_i),
    .csr_ack_o(config_regs__csr_ack_o),
    .csr_dat_o(config_regs__csr_dat_o),
    .csr_err_o(config_regs__csr_err_o),
    .sts_init_done(tie__config_regs__sts_init_done),
    .sts_cal_done(tie__config_regs__sts_cal_done),
    .sts_cal_fail(tie__config_regs__sts_cal_fail),
    .sts_bist_done(tie__config_regs__sts_bist_done),
    .sts_bist_fail(tie__config_regs__sts_bist_fail),
    .sts_ref_pending_cnt(refresh_ctrl__ref_pending_cnt),
    .sts_self_refresh_active(tie__config_regs__sts_self_refresh_active),
    .sts_ecc_ce_count(tie__config_regs__sts_ecc_ce_count),
    .sts_ecc_ue_event(tie__config_regs__sts_ecc_ue_event),
    .sts_ref_starve_event(refresh_ctrl__ref_starve_flag),
    .sts_init_fail_event(tie__config_regs__sts_init_fail_event),
    .sts_bist_fail_addr(tie__config_regs__sts_bist_fail_addr),
    .cfg_tRCD_nCK(config_regs__cfg_tRCD_nCK),
    .cfg_tRP_nCK(config_regs__cfg_tRP_nCK),
    .cfg_tRAS_nCK(config_regs__cfg_tRAS_nCK),
    .cfg_tRC_nCK(config_regs__cfg_tRC_nCK),
    .cfg_tRRD_nCK(config_regs__cfg_tRRD_nCK),
    .cfg_tWTR_nCK(config_regs__cfg_tWTR_nCK),
    .cfg_tFAW_nCK(config_regs__cfg_tFAW_nCK),
    .cfg_tRFC_nCK(config_regs__cfg_tRFC_nCK),
    .cfg_tWR_nCK(config_regs__cfg_tWR_nCK),
    .cfg_tRTP_nCK(config_regs__cfg_tRTP_nCK),
    .cfg_CL_nCK(config_regs__cfg_CL_nCK),
    .cfg_CWL_nCK(config_regs__cfg_CWL_nCK),
    .cfg_tCCD_nCK(config_regs__cfg_tCCD_nCK),
    .cfg_tREFI_nCK(config_regs__cfg_tREFI_nCK),
    .cfg_sched_policy(config_regs__cfg_sched_policy),
    .cfg_row_policy(config_regs__cfg_row_policy),
    .cfg_self_ref_mode(config_regs__cfg_self_ref_mode),
    .cfg_ecc_enable(config_regs__cfg_ecc_enable),
    .cfg_bist_start(config_regs__cfg_bist_start),
    .cfg_force_refresh(config_regs__cfg_force_refresh),
    .cfg_force_self_ref(config_regs__cfg_force_self_ref),
    .cfg_max_postpone(config_regs__cfg_max_postpone),
    .cfg_urgent_threshold(config_regs__cfg_urgent_threshold),
    .cfg_ref_priority(config_regs__cfg_ref_priority),
    .cfg_bist_pattern(config_regs__cfg_bist_pattern),
    .cfg_bist_addr_mode(config_regs__cfg_bist_addr_mode),
    .cfg_bist_addr_start(config_regs__cfg_bist_addr_start),
    .cfg_bist_addr_end(config_regs__cfg_bist_addr_end)
  );
  data_path u_data_path (
    .clk(clk),
    .rst_n(rst_n),
    .cmd_wr_valid(cmd_gen__fb_wr_valid),
    .cmd_rd_valid(cmd_gen__fb_rd_valid),
    .cmd_aux(cmd_gen__cmd_out_aux),
    .wr_data_valid(xg__data_path__wr_data_valid),
    .wr_data(wb_port__req_wdata),
    .wr_mask(wb_port__req_wmask),
    .wr_data_ready(data_path__wr_data_ready),
    .rd_rsp_valid(data_path__rd_rsp_valid),
    .rd_rsp_data(data_path__rd_rsp_data),
    .rd_rsp_aux(data_path__rd_rsp_aux),
    .cfg_CL_nCK(config_regs__cfg_CL_nCK),
    .cfg_CWL_nCK(config_regs__cfg_CWL_nCK),
    .ddr_dq_o(data_path__ddr_dq_o),
    .ddr_dq_oe(data_path__ddr_dq_oe),
    .ddr_dq_i(stub__u_dram__ddr_dq_i),
    .ddr_dm_o(data_path__ddr_dm_o),
    .ddr_dqs_o(data_path__ddr_dqs_o),
    .ddr_dqs_oe(data_path__ddr_dqs_oe),
    .ddr_dqs_i(stub__u_dram__ddr_dqs_i)
  );
  refresh_ctrl u_refresh_ctrl (
    .clk(clk),
    .rst_n(rst_n),
    .init_done(tie__refresh_ctrl__init_done),
    .cfg_force_refresh(config_regs__cfg_force_refresh),
    .cfg_tREFI_nCK(config_regs__cfg_tREFI_nCK),
    .cfg_max_postpone(config_regs__cfg_max_postpone),
    .cfg_urgent_threshold(config_regs__cfg_urgent_threshold),
    .cfg_ref_priority(config_regs__cfg_ref_priority),
    .ref_required(refresh_ctrl__ref_required),
    .ref_urgent(refresh_ctrl__ref_urgent),
    .ref_ack(scheduler__ref_ack),
    .ref_pending_cnt(refresh_ctrl__ref_pending_cnt),
    .ref_starve_flag(refresh_ctrl__ref_starve_flag)
  );
  scheduler u_scheduler (
    .clk(clk),
    .rst_n(rst_n),
    .q_valid(cmd_queue__entry_valid),
    .q_row(cmd_queue__entry_row),
    .q_col(cmd_queue__entry_col),
    .q_bank(cmd_queue__entry_bank),
    .q_we(cmd_queue__entry_we),
    .q_aux(cmd_queue__entry_aux),
    .bank_is_active(bank_tracker__bank_is_active),
    .bank_open_row(bank_tracker__bank_open_row),
    .bank_act_allowed(bank_tracker__bank_act_allowed),
    .bank_rd_allowed(bank_tracker__bank_rd_allowed),
    .bank_wr_allowed(bank_tracker__bank_wr_allowed),
    .bank_pre_allowed(bank_tracker__bank_pre_allowed),
    .ref_required(refresh_ctrl__ref_required),
    .ref_urgent(refresh_ctrl__ref_urgent),
    .ref_ack(scheduler__ref_ack),
    .cmd_valid(scheduler__cmd_valid),
    .cmd_type(scheduler__cmd_type),
    .cmd_row(scheduler__cmd_row),
    .cmd_col(scheduler__cmd_col),
    .cmd_bank(scheduler__cmd_bank),
    .cmd_we(scheduler__cmd_we),
    .cmd_aux(scheduler__cmd_aux),
    .deq_grant(scheduler__deq_grant),
    .deq_idx(scheduler__deq_idx)
  );
  wb_port u_wb_port (
    .clk(clk),
    .rst_n(rst_n),
    .wb_cyc_i(free__wb_port__wb_cyc_i),
    .wb_stb_i(free__wb_port__wb_stb_i),
    .wb_we_i(free__wb_port__wb_we_i),
    .wb_adr_i(free__wb_port__wb_adr_i),
    .wb_dat_i(free__wb_port__wb_dat_i),
    .wb_sel_i(free__wb_port__wb_sel_i),
    .wb_bte_i(free__wb_port__wb_bte_i),
    .wb_cti_i(free__wb_port__wb_cti_i),
    .wb_ack_o(wb_port__wb_ack_o),
    .wb_dat_o(wb_port__wb_dat_o),
    .wb_stall_o(wb_port__wb_stall_o),
    .wb_err_o(wb_port__wb_err_o),
    .req_valid(wb_port__req_valid),
    .req_we(wb_port__req_we),
    .req_addr(wb_port__req_addr),
    .req_wdata(wb_port__req_wdata),
    .req_wmask(wb_port__req_wmask),
    .req_aux(wb_port__req_aux),
    .req_ready(cmd_queue__enq_ready),
    .rsp_valid(data_path__rd_rsp_valid),
    .rsp_rdata(data_path__rd_rsp_data),
    .rsp_aux(data_path__rd_rsp_aux)
  );

endmodule
