// GENERATED by Validation/structural/chain_harness_gen.py --formal — DO NOT EDIT.
//
// Path     : path_08_init_to_cal
// Blocks   : calibration, init_fsm
//
// Formal top for JasperGold: the path's blocks wired per integration_map.json,
// host inputs and DRAM data left free, CSR/status inputs tied as in simulation.
// The generated SVA attach through their bind files; nothing here checks anything.

module chain_formal (
    input logic clk,
    input logic rst_n
);

  logic init_fsm__init_done;
  logic calibration__cal_done;
  logic calibration__cal_fail;
  logic calibration__zqcs_req;
  logic xg__calibration__zqcs_ack;
  logic tie__init_fsm__enable;
  logic init_fsm__init_fail;
  logic init_fsm__init_cmd_valid;
  logic [3:0] init_fsm__init_cmd;
  logic [14:0] init_fsm__init_addr;
  logic [2:0] init_fsm__init_bank;
  logic init_fsm__init_cke;
  logic init_fsm__init_reset_n;
  logic [3:0] init_fsm__init_state;

  assign xg__calibration__zqcs_ack = calibration__zqcs_req;   // expr glue
  assign tie__init_fsm__enable = 1'b1;



  calibration u_calibration (
    .clk(clk),
    .rst_n(rst_n),
    .init_done(init_fsm__init_done),
    .cal_done(calibration__cal_done),
    .cal_fail(calibration__cal_fail),
    .zqcs_req(calibration__zqcs_req),
    .zqcs_ack(xg__calibration__zqcs_ack)
  );
  init_fsm u_init_fsm (
    .clk(clk),
    .rst_n(rst_n),
    .enable(tie__init_fsm__enable),
    .init_done(init_fsm__init_done),
    .init_fail(init_fsm__init_fail),
    .init_cmd_valid(init_fsm__init_cmd_valid),
    .init_cmd(init_fsm__init_cmd),
    .init_addr(init_fsm__init_addr),
    .init_bank(init_fsm__init_bank),
    .init_cke(init_fsm__init_cke),
    .init_reset_n(init_fsm__init_reset_n),
    .init_state(init_fsm__init_state)
  );

endmodule
