#!/usr/bin/env python3
"""
packager_agent.py

Goal:
- Take a bundle that has already been validated by Intake Agent
- Create an OpenROAD-flow-scripts runnable design directory:
    $ORFS_DIR/flow/designs/<platform>/<design_name>/
      - config.mk
      - constraint.sdc
      - src/<rtl>

Outputs a machine-readable packager_report.json plus helper files to run the flow.

Usage:
  python packager_agent.py \
    --bundle_dir /path/to/frontend_bundle \
    --intake_report /path/to/intake_out/<bundle_name>/intake_report.json

Optional:
  --env_file .env
  --design_name config_regs
  --platform sky130hd
  --clock_port clk
  --clock_period_ns 5.0
  --out_dir /path/to/package_out
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ----------------------------
# .env loader (no dependencies)
# (kept intentionally similar to intake_agent.py)
# ----------------------------

def load_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return
    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        k = k.strip()
        v = v.strip().strip('"').strip("'").strip()
        os.environ.setdefault(k, v)


# ----------------------------
# Findings / report structures
# ----------------------------

@dataclass
class Finding:
    severity: str  # "ERROR" | "WARNING" | "INFO"
    code: str
    message: str
    fix: str


def add_finding(lst: List[Finding], severity: str, code: str, message: str, fix: str) -> None:
    lst.append(Finding(severity=severity, code=code, message=message, fix=fix))


def status_from_findings(errors: List[Finding], warnings: List[Finding]) -> str:
    if errors:
        return "FAIL"
    if warnings:
        return "PASS_WITH_WARNINGS"
    return "PASS"


def write_json(path: Path, obj: Any) -> None:
    path.write_text(json.dumps(obj, indent=2))


def write_text(path: Path, s: str) -> None:
    path.write_text(s if s.endswith("\n") else (s + "\n"), encoding="utf-8")


# ----------------------------
# Bundle/manifest discovery (same preference order as intake)
# ----------------------------

def find_manifest_json(bundle_dir: Path) -> Optional[Path]:
    direct = bundle_dir / "manifest.json"
    if direct.exists():
        return direct
    exact = list(bundle_dir.glob("*_manifest.json"))
    if exact:
        return sorted(exact, key=lambda p: len(p.name))[0]
    broad = list(bundle_dir.glob("*manifest*.json"))
    if broad:
        return sorted(broad, key=lambda p: len(p.name))[0]
    return None


# ----------------------------
# Helpers: infer clock/reset from manifest
# ----------------------------

def infer_clock_reset(manifest: Dict[str, Any]) -> Tuple[Optional[str], Optional[str]]:
    clock_port = None
    reset_port = None
    ports = manifest.get("ports", {})
    clock_reset = ports.get("clock_reset", [])
    if not isinstance(clock_reset, list):
        return None, None

    for p in clock_reset:
        if not isinstance(p, dict):
            continue
        n = p.get("name")
        d = p.get("dir")
        if not isinstance(n, str) or d != "input":
            continue
        ln = n.lower()
        if clock_port is None and "clk" in ln:
            clock_port = n
        if reset_port is None and ("rst" in ln or "reset" in ln):
            reset_port = n
    return clock_port, reset_port


def safe_design_name(s: str) -> str:
    # ORFS design dirs are happiest with [A-Za-z0-9_]
    s = s.strip()
    s = re.sub(r"[^A-Za-z0-9_]+", "_", s)
    return s or "design"


# ----------------------------
# RTL normalization
# ----------------------------

# Share of the clock period budgeted to logic outside the block on every input and
# output (ORFS convention, as in flow/designs/sky130hd/gcd and ibex). Without it only
# register-to-register paths are timed and paths through ports go unchecked.
SDC_IO_DELAY_PCT = 0.2


def build_sdc(module_name: str, clock_port: str, clock_period_ns: float,
              io_pct: float = SDC_IO_DELAY_PCT) -> str:
    """
    constraint.sdc for one block, in the ORFS style: the period lives in
    `set clk_period`, which create_clock and the I/O delays both use.
    pipeline.py _patch_clock_period rewrites that line when the Fmax tuner runs.
    """
    return (
        "# Auto-generated by packager_agent.py (ORFS convention, as in designs/sky130hd/gcd)\n"
        f"current_design {module_name}\n"
        "\n"
        "set clk_name core_clk\n"
        f"set clk_port_name {clock_port}\n"
        f"set clk_period {clock_period_ns}\n"
        f"set clk_io_pct {io_pct}\n"
        "\n"
        "set clk_port [get_ports $clk_port_name]\n"
        "\n"
        "create_clock -name $clk_name -period $clk_period $clk_port\n"
        "\n"
        "# Budget part of the period to logic outside this block on every port, so\n"
        "# paths through ports are timed, not only register-to-register paths.\n"
        "set non_clock_inputs [all_inputs -no_clocks]\n"
        "\n"
        "set_input_delay [expr $clk_period * $clk_io_pct] -clock $clk_name $non_clock_inputs\n"
        "set_output_delay [expr $clk_period * $clk_io_pct] -clock $clk_name [all_outputs]\n"
    )


def _rtl_needs_slang(rtl_path: Path) -> bool:
    """
    Returns True if the RTL contains SystemVerilog constructs that require
    the slang frontend — specifically unpacked array port dimensions,
    type cast syntax, or struct/aggregate literals.
    """
    try:
        text = rtl_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False
    # Strip single-line comments before matching so trailing // don't interfere
    stripped = re.sub(r"//.*$", "", text, flags=re.MULTILINE)
    # Unpacked array port dimensions e.g. "input logic [W-1:0] port_name [DEPTH]"
    unpacked_port_re = re.compile(
        r"^\s*(input|output|inout)\b.*\b\w+\s*\[\w+\]\s*[,;)]?\s*$",
        re.MULTILINE | re.IGNORECASE,
    )
    if unpacked_port_re.search(stripped):
        return True
    # SystemVerilog type cast e.g. "int'(x)" or "logic'(x)"
    typecast_re = re.compile(
        r"\b(int|logic|bit|byte|shortint|longint|integer|time)\s*'\s*\(",
        re.MULTILINE,
    )
    if typecast_re.search(stripped):
        return True
    # SystemVerilog aggregate/struct literals e.g. "'{data: x, mask: y}" or "'0"
    aggregate_re = re.compile(
        r"'\s*[\{0-9]",
        re.MULTILINE,
    )
    if aggregate_re.search(stripped):
        return True
    return False


def _split_line_comment(line: str) -> Tuple[str, str]:
    """
    Split a source line into (code, comment) at its trailing `//`.

    Used by _normalize_rtl so line-joining decisions are made on code alone.
    Does not honour `//` inside a string literal, which does not occur in a
    port declaration.
    """
    idx = line.find("//")
    if idx < 0:
        return line, ""
    return line[:idx], line[idx:]


def _normalize_rtl(rtl_path: Path) -> None:
    """
    Normalize RTL formatting issues that trip up Yosys:

    1. Join split port declarations — when a port direction keyword
       (input/output/inout) appears on a line with no following identifier,
       the port name is on the next line. Join them onto one line.

       Before:
           input  logic [DEPTH-1:0]
           q_valid,
       After:
           input  logic [DEPTH-1:0] q_valid,

    2. Strip Windows CRLF line endings.
    """
    try:
        text = rtl_path.read_text(encoding="utf-8", errors="ignore")
    except Exception as e:
        print(f"[packager] WARNING: could not read RTL for normalization: {e}")
        return

    lines = text.splitlines()
    normalized: List[str] = []
    i = 0
    port_dir_re = re.compile(r"^\s*(input|output|inout)\b", re.IGNORECASE)
    # A port declaration is UNFINISHED — its identifier is on the next line —
    # when its code portion ends in a packed range or a bare type keyword.
    # Anything else (an identifier, a comma, a close-paren) means the
    # declaration is complete and must NOT be joined.
    #
    # Matched against code only. The previous pattern tested the raw line for
    # the *presence* of an identifier, which a trailing comment like
    # "// {cs_n, ras_n, cas_n, we_n}" defeated: the line looked unfinished, the
    # next port was joined onto the unterminated "//", and that port was
    # silently deleted from the design.
    needs_join_re = re.compile(
        r"(\]|\b(?:logic|wire|reg|bit|signed|unsigned|int|integer|byte))\s*$",
        re.IGNORECASE,
    )

    while i < len(lines):
        line = lines[i]
        code, comment = _split_line_comment(line)
        # A port direction line whose identifier is still on the next line
        if port_dir_re.match(code) and needs_join_re.search(code.rstrip()):
            # Peek at next non-empty line and join it
            j = i + 1
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j < len(lines):
                next_code, next_comment = _split_line_comment(lines[j])
                # Comments are re-emitted AFTER the joined code. Appending the
                # next line onto an unterminated "//" would comment it out.
                tails = [c[2:].strip() for c in (comment, next_comment) if c]
                tails = [t for t in tails if t]
                tail = ("  // " + "  ".join(tails)) if tails else ""
                joined = code.rstrip() + " " + next_code.strip() + tail
                normalized.append(joined)
                i = j + 1
                continue
        normalized.append(line)
        i += 1

    result = "\n".join(normalized) + "\n"
    try:
        rtl_path.write_text(result, encoding="utf-8")
    except Exception as e:
        print(f"[packager] WARNING: could not write normalized RTL: {e}")


# ----------------------------
# Core packager
# ----------------------------

def package_bundle(
    bundle_dir: Path,
    intake_report_path: Path,
    out_dir: Path,
    orfs_dir: Optional[Path],
    design_name: Optional[str],
    platform: Optional[str],
    clock_port: Optional[str],
    clock_period_ns: Optional[float],
) -> Dict[str, Any]:
    errors: List[Finding] = []
    warnings: List[Finding] = []
    infos: List[Finding] = []
    facts: Dict[str, Any] = {}

    facts["bundle_dir"] = str(bundle_dir)
    facts["intake_report_path"] = str(intake_report_path)
    facts["out_dir"] = str(out_dir)
    facts["env"] = {
        "ORFS_DIR": os.environ.get("ORFS_DIR", "").strip(),
        "OUT_ROOT": os.environ.get("OUT_ROOT", "").strip(),
        "PLATFORM": os.environ.get("PLATFORM", "").strip(),
        "MAKE_JOBS": os.environ.get("MAKE_JOBS", "").strip(),
    }

    if not bundle_dir.exists():
        add_finding(errors, "ERROR", "IO-001", f"Bundle dir not found: {bundle_dir}", "Pass the correct --bundle_dir.")
        return _finalize(errors, warnings, infos, facts, packaged=None)

    if not intake_report_path.exists():
        add_finding(errors, "ERROR", "IO-002", f"Intake report not found: {intake_report_path}", "Pass the correct --intake_report.")
        return _finalize(errors, warnings, infos, facts, packaged=None)

    # Load intake report and enforce gating
    try:
        intake = json.loads(intake_report_path.read_text())
    except Exception as e:
        add_finding(errors, "ERROR", "INTAKE-001", f"Failed to parse intake_report.json: {e}", "Regenerate intake outputs.")
        return _finalize(errors, warnings, infos, facts, packaged=None)

    intake_status = intake.get("status")
    facts["intake_status"] = intake_status

    if intake_status not in ("PASS", "PASS_WITH_WARNINGS"):
        add_finding(
            errors, "ERROR", "INTAKE-010",
            f"Refusing to package because intake status is {intake_status!r} (must be PASS or PASS_WITH_WARNINGS).",
            "Fix the intake errors first, then re-run packager."
        )
        return _finalize(errors, warnings, infos, facts, packaged=None)

    # Load manifest
    manifest_path = find_manifest_json(bundle_dir)
    if not manifest_path:
        add_finding(errors, "ERROR", "MAN-001", "No manifest JSON found in bundle.", "Include manifest.json or *_manifest.json.")
        return _finalize(errors, warnings, infos, facts, packaged=None)

    try:
        manifest = json.loads(manifest_path.read_text())
    except Exception as e:
        add_finding(errors, "ERROR", "MAN-002", f"Manifest JSON parse failed: {e}", "Fix manifest formatting.")
        return _finalize(errors, warnings, infos, facts, packaged=None)

    # Basic required keys (intake should have enforced, but keep packager robust)
    if "file" not in manifest or "module_name" not in manifest:
        add_finding(errors, "ERROR", "MAN-010", "Manifest missing 'file' and/or 'module_name'.", "Regenerate manifest via frontend.")
        return _finalize(errors, warnings, infos, facts, packaged=None)

    rtl_files = manifest["file"] if isinstance(manifest["file"], list) else [manifest["file"]]
    rtl_files = [str(f).strip() for f in rtl_files]
    rtl_paths = [bundle_dir / f for f in rtl_files]
    missing = [str(p) for p in rtl_paths if not p.exists()]
    if missing:
        add_finding(errors, "ERROR", "IO-010", f"RTL file(s) not found: {missing}",
                    "Ensure the bundle contains every file listed in manifest.file.")
        return _finalize(errors, warnings, infos, facts, packaged=None)
    names = [p.name for p in rtl_paths]
    dupes = sorted({n for n in names if names.count(n) > 1})
    if dupes:
        add_finding(errors, "ERROR", "IO-011", f"manifest.file lists several sources with the same filename: {dupes}",
                    "Give every source a unique filename; they are copied into one src/ directory.")
        return _finalize(errors, warnings, infos, facts, packaged=None)
    rtl_path = rtl_paths[0]

    # Resolve platform
    resolved_platform = (
        platform
        or manifest.get("platform")
        or (os.environ.get("PLATFORM") or "").strip()
        or None
    )
    if not resolved_platform:
        add_finding(errors, "ERROR", "OR-001", "No PLATFORM resolved.", "Pass --platform, set PLATFORM in .env, or add manifest.platform.")
        return _finalize(errors, warnings, infos, facts, packaged=None)

    # Resolve design name
    resolved_design_name = safe_design_name(design_name or bundle_dir.name)

    # Resolve clock/reset inference
    inferred_clk, inferred_rst = infer_clock_reset(manifest)

    resolved_clock_port = clock_port or manifest.get("clock_port") or inferred_clk
    resolved_reset_port = manifest.get("reset_port") or inferred_rst  # informational only

    # Resolve clock period
    defaulted_clock_period = False
    if clock_period_ns is not None:
        resolved_clock_period = float(clock_period_ns)
    elif manifest.get("clock_period_ns") is not None:
        resolved_clock_period = float(manifest["clock_period_ns"])
    else:
        resolved_clock_period = 10.0  # default policy
        defaulted_clock_period = True
        add_finding(
            warnings, "WARNING", "OR-003",
            "clock_period_ns not provided; defaulting to 10.0 ns.",
            "Add manifest.clock_period_ns (or pass --clock_period_ns) to control timing constraints."
        )

    if not resolved_clock_port:
        add_finding(
            warnings, "WARNING", "OR-002",
            "Clock port not identified; constraint.sdc will be generated without a create_clock.",
            "Add manifest.clock_port or ensure manifest.ports.clock_reset includes the clock."
        )

    # Resolve ORFS_DIR
    resolved_orfs_dir = orfs_dir or Path((os.environ.get("ORFS_DIR") or "").strip()) if (os.environ.get("ORFS_DIR") or "").strip() else None
    if not resolved_orfs_dir:
        add_finding(
            errors, "ERROR", "ORFS-001",
            "ORFS_DIR not set/provided; cannot create ORFS design directory.",
            "Set ORFS_DIR in .env or pass --orfs_dir."
        )
        return _finalize(errors, warnings, infos, facts, packaged=None)

    flow_dir = resolved_orfs_dir / "flow"
    makefile = flow_dir / "Makefile"
    if not makefile.exists():
        add_finding(
            errors, "ERROR", "ORFS-002",
            f"ORFS flow Makefile not found at: {makefile}",
            "Ensure ORFS_DIR points to the root of OpenROAD-flow-scripts."
        )
        return _finalize(errors, warnings, infos, facts, packaged=None)

    # Create ORFS design directory
    design_dir = flow_dir / "designs" / resolved_platform / resolved_design_name
    src_dir = design_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    # Copy every source into src/ and normalize formatting
    dst_rtl_paths = []
    for src_path in rtl_paths:
        dst = src_dir / src_path.name
        shutil.copy2(src_path, dst)
        _normalize_rtl(dst)
        dst_rtl_paths.append(dst)
    dst_rtl_path = dst_rtl_paths[0]

    # Any source needing full SystemVerilog elaboration (unpacked array ports, type
    # casts, aggregate literals) puts the whole design on the slang frontend.
    slang_sources = [p.name for p in dst_rtl_paths if _rtl_needs_slang(p)]
    needs_slang = bool(slang_sources)
    if needs_slang:
        print(f"[packager] SystemVerilog constructs needing slang found in {slang_sources} — "
              f"enabling the slang SV frontend.")

    # Generate constraint.sdc
    sdc_path = design_dir / "constraint.sdc"
    if resolved_clock_port:
        sdc = build_sdc(str(manifest.get("module_name")), resolved_clock_port, resolved_clock_period)
    else:
        sdc = (
            "# Auto-generated by packager_agent.py\n"
            "# NOTE: clock port unknown; add create_clock once clock_port is known.\n"
        )
    write_text(sdc_path, sdc)

    # Generate config.mk (minimal, runner can override via make vars if desired)
    config_mk_path = design_dir / "config.mk"
    # Use forward slashes for make friendliness
    verilog_rel = f"designs/{resolved_platform}/{resolved_design_name}/src/{dst_rtl_path.name}"
    sdc_rel = f"designs/{resolved_platform}/{resolved_design_name}/{sdc_path.name}"

    config_lines = [
        "# Auto-generated by packager_agent.py",
        f"export DESIGN_NAME = {manifest.get('module_name')}",
        f"export PLATFORM = {resolved_platform}",
        "export VERILOG_FILES = " + " ".join(
            f"/OpenROAD-flow-scripts/flow/designs/{resolved_platform}/{resolved_design_name}/src/{p.name}"
            for p in dst_rtl_paths),
        f"export SDC_FILE      = /OpenROAD-flow-scripts/flow/designs/{resolved_platform}/{resolved_design_name}/constraint.sdc",
        f"export CLOCK_PERIOD  = {resolved_clock_period}",
        f"export CORE_UTILIZATION = 20",
        f"export CORE_MARGIN = 10",
        f"export TNS_END_PERCENT = 100",
        f"export ANTENNA_REPAIR = 1",
    ]
    if needs_slang:
        config_lines.append("export SYNTH_HDL_FRONTEND = slang")
    if resolved_clock_port:
        config_lines.append(f"export CLOCK_PORT = {resolved_clock_port}")
    # Flow settings this design needs, declared by the manifest (e.g. SYNTH_ARGS).
    orfs_config = manifest.get("orfs_config") or {}
    if isinstance(orfs_config, dict) and orfs_config:
        config_lines.append("# From manifest.orfs_config")
        config_lines += [f"export {k} = {v}" for k, v in orfs_config.items()]
        print(f"[packager] Applied manifest.orfs_config: {orfs_config}")
    config_lines = [l for l in config_lines if l]
    write_text(config_mk_path, "\n".join(config_lines) + "\n")

    # Write packaging outputs
    out_dir.mkdir(parents=True, exist_ok=True)

    packaged_manifest = dict(manifest)
    packaged_manifest["packager"] = {
        "resolved": {
            "platform": resolved_platform,
            "design_name": resolved_design_name,
            "rtl_filename": rtl_path.name,
            "rtl_files": [p.name for p in dst_rtl_paths],
            "orfs_config": orfs_config,
            "clock_port": resolved_clock_port,
            "reset_port": resolved_reset_port,
            "clock_period_ns": resolved_clock_period,
            "sdc_io_delay_pct": SDC_IO_DELAY_PCT if resolved_clock_port else None,
            "orfs_dir": str(resolved_orfs_dir),
            "orfs_design_dir": str(design_dir),
            "design_config_mk": str(config_mk_path),
        },
        "policy": {
            "clock_period_defaulted": defaulted_clock_period,
        },
    }

    write_json(out_dir / "packaged_manifest.json", packaged_manifest)
    write_text(out_dir / "orfs_design_path.txt", str(design_dir))

    # Convenience script for your future runner (and for you now)
    jobs = (os.environ.get("MAKE_JOBS") or "").strip()
    jobs_arg = jobs if jobs.startswith("-j") else (f"-j{jobs}" if jobs else "")
    rel_cfg = f"designs/{resolved_platform}/{resolved_design_name}/config.mk"
    run_sh = (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n\n"
        f"cd {flow_dir}\n"
        f"make {jobs_arg} DESIGN_CONFIG={rel_cfg}\n"
    )
    run_path = out_dir / "run_in_orfs.sh"
    write_text(run_path, run_sh)
    try:
        os.chmod(run_path, 0o755)
    except Exception:
        pass

    readme = (
        f"# Packaged OpenROAD Design: {resolved_design_name}\n\n"
        "This directory was generated by `packager_agent.py`.\n\n"
        "## Where the ORFS design lives\n"
        f"- `{design_dir}`\n\n"
        "## How to run (manual)\n"
        "```bash\n"
        f"cd {flow_dir}\n"
        f"make {jobs_arg} DESIGN_CONFIG=designs/{resolved_platform}/{resolved_design_name}/config.mk\n"
        "```\n\n"
        "## Notes\n"
        f"- RTL copied to: `{dst_rtl_path}`\n"
        f"- SDC: `{sdc_path}`\n"
        f"- Config: `{config_mk_path}`\n"
    )
    write_text(out_dir / "README.md", readme)

    facts.update({
        "resolved_platform": resolved_platform,
        "resolved_design_name": resolved_design_name,
        "rtl_src": str(rtl_path),
        "rtl_dst": str(dst_rtl_path),
        "design_dir": str(design_dir),
        "config_mk_path": str(config_mk_path),
        "sdc_path": str(sdc_path),
        "defaulted_clock_period": defaulted_clock_period,
    })

    add_finding(infos, "INFO", "OK-001", "Packaging completed and ORFS design directory created.", "You can now run make with DESIGN_CONFIG=...")

    return _finalize(errors, warnings, infos, facts, packaged=packaged_manifest)


def _finalize(errors: List[Finding], warnings: List[Finding], infos: List[Finding], facts: Dict[str, Any], packaged: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    status = status_from_findings(errors, warnings)
    return {
        "status": status,
        "errors": [asdict(e) for e in errors],
        "warnings": [asdict(w) for w in warnings],
        "info": [asdict(i) for i in infos],
        "facts": facts,
        "packaged_manifest": packaged,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle_dir", required=True, type=Path)
    ap.add_argument("--intake_report", required=True, type=Path)
    ap.add_argument("--env_file", type=Path, default=Path(".env"))
    ap.add_argument("--out_dir", type=Path, default=None)

    ap.add_argument("--orfs_dir", type=Path, default=None)
    ap.add_argument("--design_name", type=str, default=None)
    ap.add_argument("--platform", type=str, default=None)
    ap.add_argument("--clock_port", type=str, default=None)
    ap.add_argument("--clock_period_ns", type=float, default=None)

    args = ap.parse_args()

    load_env_file(args.env_file)

    if args.out_dir is None:
        out_root = (os.environ.get("OUT_ROOT") or "").strip()
        if out_root:
            args.out_dir = Path(out_root) / "package" / args.bundle_dir.name
        else:
            args.out_dir = Path("./package_out") / args.bundle_dir.name

    result = package_bundle(
        bundle_dir=args.bundle_dir,
        intake_report_path=args.intake_report,
        out_dir=args.out_dir,
        orfs_dir=args.orfs_dir,
        design_name=args.design_name,
        platform=args.platform,
        clock_port=args.clock_port,
        clock_period_ns=args.clock_period_ns,
    )

    # Always write report
    args.out_dir.mkdir(parents=True, exist_ok=True)
    write_json(args.out_dir / "packager_report.json", {
        "status": result["status"],
        "errors": result["errors"],
        "warnings": result["warnings"],
        "info": result["info"],
        "facts": result["facts"],
    })

    # Exit codes similar to intake
    if result["status"] == "PASS":
        return 0
    if result["status"] == "PASS_WITH_WARNINGS":
        return 1
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
