// ddr3_controller -- generated by Frontend2/scripts/generate_top.py
// Follows backend/Frontend2/TOP_LEVEL_SPEC_2026-09-24.md.
// 77 direct connections, 0 registered glue group(s), 1 combinational glue expression(s).
// KNOWN GAP: calibration.zqcs_req / calibration.zqcs_ack: no block issues or arbitrates ZQCS requests yet, so nothing can drive zqcs_ack from inside the design. Left as external pins rather than auto-acking (auto-ack would silently hide a real missing consumer).

module ddr3_controller (
    input  logic clk,
    input  logic rst_n,
    input  logic              calibration_zqcs_ack,
    input  logic [7:0]        config_regs_csr_adr_i,
    input  logic              config_regs_csr_cyc_i,
    input  logic [31:0]       config_regs_csr_dat_i,
    input  logic [3:0]        config_regs_csr_sel_i,
    input  logic              config_regs_csr_stb_i,
    input  logic              config_regs_csr_we_i,
    input  logic              config_regs_sts_bist_done,
    input  logic              config_regs_sts_bist_fail,
    input  logic [12:0]       config_regs_sts_bist_fail_addr,
    input  logic [15:0]       config_regs_sts_ecc_ce_count,
    input  logic              config_regs_sts_ecc_ue_event,
    input  logic              config_regs_sts_self_refresh_active,
    input  logic [15:0]       data_path_ddr_dq_i,
    input  logic              data_path_ddr_dqs_i,
    input  logic              init_fsm_enable,
    input  logic [28:0]       wb_port_wb_adr_i,
    input  logic [1:0]        wb_port_wb_bte_i,
    input  logic [2:0]        wb_port_wb_cti_i,
    input  logic              wb_port_wb_cyc_i,
    input  logic [31:0]       wb_port_wb_dat_i,
    input  logic [3:0]        wb_port_wb_sel_i,
    input  logic              wb_port_wb_stb_i,
    input  logic              wb_port_wb_we_i,
    output logic              addr_decoder_dec_rank,
    output logic              bank_tracker_all_banks_idle,
    output logic              bank_tracker_faw_allows_act,
    output logic              calibration_zqcs_req,
    output logic              cmd_gen_cmd_out_valid,
    output logic              cmd_gen_cmd_out_we,
    output logic [14:0]       cmd_gen_ddr_addr,
    output logic [2:0]        cmd_gen_ddr_bank,
    output logic              cmd_gen_ddr_cke,
    output logic [3:0]        cmd_gen_ddr_cmd,
    output logic              cmd_gen_ddr_odt,
    output logic              cmd_gen_ddr_reset_n,
    output logic [4:0]        cmd_queue_queue_count,
    output logic              cmd_queue_queue_empty,
    output logic              cmd_queue_queue_full,
    output logic [28:0]       config_regs_cfg_bist_addr_end,
    output logic              config_regs_cfg_bist_addr_mode,
    output logic [28:0]       config_regs_cfg_bist_addr_start,
    output logic [2:0]        config_regs_cfg_bist_pattern,
    output logic              config_regs_cfg_bist_start,
    output logic              config_regs_cfg_ecc_enable,
    output logic              config_regs_cfg_force_self_ref,
    output logic              config_regs_cfg_row_policy,
    output logic              config_regs_cfg_sched_policy,
    output logic [1:0]        config_regs_cfg_self_ref_mode,
    output logic              config_regs_csr_ack_o,
    output logic [31:0]       config_regs_csr_dat_o,
    output logic              config_regs_csr_err_o,
    output logic [1:0]        data_path_ddr_dm_o,
    output logic [15:0]       data_path_ddr_dq_o,
    output logic              data_path_ddr_dq_oe,
    output logic              data_path_ddr_dqs_o,
    output logic              data_path_ddr_dqs_oe,
    output logic              data_path_wr_data_ready,
    output logic [14:0]       init_fsm_init_addr,
    output logic [2:0]        init_fsm_init_bank,
    output logic              init_fsm_init_cke,
    output logic [3:0]        init_fsm_init_cmd,
    output logic              init_fsm_init_cmd_valid,
    output logic              init_fsm_init_reset_n,
    output logic [3:0]        init_fsm_init_state,
    output logic              wb_port_wb_ack_o,
    output logic [31:0]       wb_port_wb_dat_o,
    output logic              wb_port_wb_err_o,
    output logic              wb_port_wb_stall_o
);

    // -- internal nets: direct block-to-block connections --
    logic [2:0]        w_addr_decoder__dec_bank;
    logic [9:0]        w_addr_decoder__dec_col;
    logic [14:0]       w_addr_decoder__dec_row;
    logic [7:0]        w_bank_tracker__bank_act_allowed;
    logic [7:0]        w_bank_tracker__bank_is_active;
    logic [14:0]       w_bank_tracker__bank_open_row[8];
    logic [7:0]        w_bank_tracker__bank_pre_allowed;
    logic [7:0]        w_bank_tracker__bank_rd_allowed;
    logic [7:0]        w_bank_tracker__bank_wr_allowed;
    logic              w_calibration__cal_done;
    logic              w_calibration__cal_fail;
    logic [3:0]        w_cmd_gen__cmd_out_aux;
    logic [2:0]        w_cmd_gen__fb_act_bank;
    logic [14:0]       w_cmd_gen__fb_act_row;
    logic              w_cmd_gen__fb_act_valid;
    logic              w_cmd_gen__fb_pre_all;
    logic [2:0]        w_cmd_gen__fb_pre_bank;
    logic              w_cmd_gen__fb_pre_valid;
    logic [2:0]        w_cmd_gen__fb_rd_bank;
    logic              w_cmd_gen__fb_rd_valid;
    logic              w_cmd_gen__fb_ref_valid;
    logic [2:0]        w_cmd_gen__fb_wr_bank;
    logic              w_cmd_gen__fb_wr_valid;
    logic              w_cmd_queue__enq_ready;
    logic [3:0]        w_cmd_queue__entry_aux[16];
    logic [2:0]        w_cmd_queue__entry_bank[16];
    logic [9:0]        w_cmd_queue__entry_col[16];
    logic [14:0]       w_cmd_queue__entry_row[16];
    logic [15:0]       w_cmd_queue__entry_valid;
    logic              w_cmd_queue__entry_we[16];
    logic [7:0]        w_config_regs__cfg_CL_nCK;
    logic [7:0]        w_config_regs__cfg_CWL_nCK;
    logic              w_config_regs__cfg_force_refresh;
    logic [3:0]        w_config_regs__cfg_max_postpone;
    logic              w_config_regs__cfg_ref_priority;
    logic [7:0]        w_config_regs__cfg_tCCD_nCK;
    logic [7:0]        w_config_regs__cfg_tFAW_nCK;
    logic [7:0]        w_config_regs__cfg_tRAS_nCK;
    logic [7:0]        w_config_regs__cfg_tRCD_nCK;
    logic [7:0]        w_config_regs__cfg_tRC_nCK;
    logic [23:0]       w_config_regs__cfg_tREFI_nCK;
    logic [7:0]        w_config_regs__cfg_tRFC_nCK;
    logic [7:0]        w_config_regs__cfg_tRP_nCK;
    logic [7:0]        w_config_regs__cfg_tRRD_nCK;
    logic [7:0]        w_config_regs__cfg_tRTP_nCK;
    logic [7:0]        w_config_regs__cfg_tWR_nCK;
    logic [7:0]        w_config_regs__cfg_tWTR_nCK;
    logic [3:0]        w_config_regs__cfg_urgent_threshold;
    logic [3:0]        w_data_path__rd_rsp_aux;
    logic [31:0]       w_data_path__rd_rsp_data;
    logic              w_data_path__rd_rsp_valid;
    logic              w_init_fsm__init_done;
    logic              w_init_fsm__init_fail;
    logic [3:0]        w_refresh_ctrl__ref_pending_cnt;
    logic              w_refresh_ctrl__ref_required;
    logic              w_refresh_ctrl__ref_starve_flag;
    logic              w_refresh_ctrl__ref_urgent;
    logic [3:0]        w_scheduler__cmd_aux;
    logic [2:0]        w_scheduler__cmd_bank;
    logic [9:0]        w_scheduler__cmd_col;
    logic [14:0]       w_scheduler__cmd_row;
    logic [3:0]        w_scheduler__cmd_type;
    logic              w_scheduler__cmd_valid;
    logic              w_scheduler__cmd_we;
    logic              w_scheduler__deq_grant;
    logic [3:0]        w_scheduler__deq_idx;
    logic              w_scheduler__ref_ack;
    logic [28:0]       w_wb_port__req_addr;
    logic [3:0]        w_wb_port__req_aux;
    logic              w_wb_port__req_valid;
    logic [31:0]       w_wb_port__req_wdata;
    logic              w_wb_port__req_we;
    logic [3:0]        w_wb_port__req_wmask;

    // -- combinational glue (see EXPR_GLUE in this script's header) --
    logic              w_expr__data_path_wr_data_valid;
    assign w_expr__data_path_wr_data_valid = w_wb_port__req_valid && w_wb_port__req_we && w_cmd_queue__enq_ready;

    addr_decoder u_addr_decoder (
        .req_addr(w_wb_port__req_addr),
        .dec_row(w_addr_decoder__dec_row),
        .dec_bank(w_addr_decoder__dec_bank),
        .dec_col(w_addr_decoder__dec_col),
        .dec_rank(addr_decoder_dec_rank)
    );

    bank_tracker u_bank_tracker (
        .clk(clk),
        .rst_n(rst_n),
        .cmd_act_valid(w_cmd_gen__fb_act_valid),
        .cmd_act_bank(w_cmd_gen__fb_act_bank),
        .cmd_act_row(w_cmd_gen__fb_act_row),
        .cmd_pre_valid(w_cmd_gen__fb_pre_valid),
        .cmd_pre_bank(w_cmd_gen__fb_pre_bank),
        .cmd_pre_all(w_cmd_gen__fb_pre_all),
        .cmd_rd_valid(w_cmd_gen__fb_rd_valid),
        .cmd_rd_bank(w_cmd_gen__fb_rd_bank),
        .cmd_wr_valid(w_cmd_gen__fb_wr_valid),
        .cmd_wr_bank(w_cmd_gen__fb_wr_bank),
        .cmd_ref_valid(w_cmd_gen__fb_ref_valid),
        .cfg_tRCD_nCK(w_config_regs__cfg_tRCD_nCK),
        .cfg_tRP_nCK(w_config_regs__cfg_tRP_nCK),
        .cfg_tRAS_nCK(w_config_regs__cfg_tRAS_nCK),
        .cfg_tRC_nCK(w_config_regs__cfg_tRC_nCK),
        .cfg_tRRD_nCK(w_config_regs__cfg_tRRD_nCK),
        .cfg_tFAW_nCK(w_config_regs__cfg_tFAW_nCK),
        .cfg_tWTR_nCK(w_config_regs__cfg_tWTR_nCK),
        .cfg_tWR_nCK(w_config_regs__cfg_tWR_nCK),
        .cfg_tRTP_nCK(w_config_regs__cfg_tRTP_nCK),
        .cfg_tCCD_nCK(w_config_regs__cfg_tCCD_nCK),
        .cfg_tRFC_nCK(w_config_regs__cfg_tRFC_nCK),
        .bank_is_active(w_bank_tracker__bank_is_active),
        .bank_open_row(w_bank_tracker__bank_open_row),
        .bank_act_allowed(w_bank_tracker__bank_act_allowed),
        .bank_rd_allowed(w_bank_tracker__bank_rd_allowed),
        .bank_wr_allowed(w_bank_tracker__bank_wr_allowed),
        .bank_pre_allowed(w_bank_tracker__bank_pre_allowed),
        .all_banks_idle(bank_tracker_all_banks_idle),
        .faw_allows_act(bank_tracker_faw_allows_act)
    );

    calibration u_calibration (
        .clk(clk),
        .rst_n(rst_n),
        .init_done(w_init_fsm__init_done),
        .cal_done(w_calibration__cal_done),
        .cal_fail(w_calibration__cal_fail),
        .zqcs_req(calibration_zqcs_req),
        .zqcs_ack(calibration_zqcs_ack)
    );

    cmd_gen u_cmd_gen (
        .clk(clk),
        .rst_n(rst_n),
        .sched_valid(w_scheduler__cmd_valid),
        .sched_type(w_scheduler__cmd_type),
        .sched_row(w_scheduler__cmd_row),
        .sched_col(w_scheduler__cmd_col),
        .sched_bank(w_scheduler__cmd_bank),
        .sched_we(w_scheduler__cmd_we),
        .sched_aux(w_scheduler__cmd_aux),
        .ddr_cmd(cmd_gen_ddr_cmd),
        .ddr_addr(cmd_gen_ddr_addr),
        .ddr_bank(cmd_gen_ddr_bank),
        .ddr_cke(cmd_gen_ddr_cke),
        .ddr_reset_n(cmd_gen_ddr_reset_n),
        .ddr_odt(cmd_gen_ddr_odt),
        .fb_act_valid(w_cmd_gen__fb_act_valid),
        .fb_act_bank(w_cmd_gen__fb_act_bank),
        .fb_act_row(w_cmd_gen__fb_act_row),
        .fb_pre_valid(w_cmd_gen__fb_pre_valid),
        .fb_pre_bank(w_cmd_gen__fb_pre_bank),
        .fb_pre_all(w_cmd_gen__fb_pre_all),
        .fb_rd_valid(w_cmd_gen__fb_rd_valid),
        .fb_rd_bank(w_cmd_gen__fb_rd_bank),
        .fb_wr_valid(w_cmd_gen__fb_wr_valid),
        .fb_wr_bank(w_cmd_gen__fb_wr_bank),
        .fb_ref_valid(w_cmd_gen__fb_ref_valid),
        .cmd_out_valid(cmd_gen_cmd_out_valid),
        .cmd_out_we(cmd_gen_cmd_out_we),
        .cmd_out_aux(w_cmd_gen__cmd_out_aux)
    );

    cmd_queue u_cmd_queue (
        .clk(clk),
        .rst_n(rst_n),
        .enq_valid(w_wb_port__req_valid),
        .enq_ready(w_cmd_queue__enq_ready),
        .enq_row(w_addr_decoder__dec_row),
        .enq_col(w_addr_decoder__dec_col),
        .enq_bank(w_addr_decoder__dec_bank),
        .enq_we(w_wb_port__req_we),
        .enq_aux(w_wb_port__req_aux),
        .deq_grant(w_scheduler__deq_grant),
        .deq_idx(w_scheduler__deq_idx),
        .entry_valid(w_cmd_queue__entry_valid),
        .entry_row(w_cmd_queue__entry_row),
        .entry_col(w_cmd_queue__entry_col),
        .entry_bank(w_cmd_queue__entry_bank),
        .entry_we(w_cmd_queue__entry_we),
        .entry_aux(w_cmd_queue__entry_aux),
        .queue_full(cmd_queue_queue_full),
        .queue_empty(cmd_queue_queue_empty),
        .queue_count(cmd_queue_queue_count)
    );

    config_regs u_config_regs (
        .clk(clk),
        .rst_n(rst_n),
        .csr_cyc_i(config_regs_csr_cyc_i),
        .csr_stb_i(config_regs_csr_stb_i),
        .csr_we_i(config_regs_csr_we_i),
        .csr_adr_i(config_regs_csr_adr_i),
        .csr_dat_i(config_regs_csr_dat_i),
        .csr_sel_i(config_regs_csr_sel_i),
        .csr_ack_o(config_regs_csr_ack_o),
        .csr_dat_o(config_regs_csr_dat_o),
        .csr_err_o(config_regs_csr_err_o),
        .sts_init_done(w_init_fsm__init_done),
        .sts_cal_done(w_calibration__cal_done),
        .sts_cal_fail(w_calibration__cal_fail),
        .sts_bist_done(config_regs_sts_bist_done),
        .sts_bist_fail(config_regs_sts_bist_fail),
        .sts_ref_pending_cnt(w_refresh_ctrl__ref_pending_cnt),
        .sts_self_refresh_active(config_regs_sts_self_refresh_active),
        .sts_ecc_ce_count(config_regs_sts_ecc_ce_count),
        .sts_ecc_ue_event(config_regs_sts_ecc_ue_event),
        .sts_ref_starve_event(w_refresh_ctrl__ref_starve_flag),
        .sts_init_fail_event(w_init_fsm__init_fail),
        .sts_bist_fail_addr(config_regs_sts_bist_fail_addr),
        .cfg_tRCD_nCK(w_config_regs__cfg_tRCD_nCK),
        .cfg_tRP_nCK(w_config_regs__cfg_tRP_nCK),
        .cfg_tRAS_nCK(w_config_regs__cfg_tRAS_nCK),
        .cfg_tRC_nCK(w_config_regs__cfg_tRC_nCK),
        .cfg_tRRD_nCK(w_config_regs__cfg_tRRD_nCK),
        .cfg_tWTR_nCK(w_config_regs__cfg_tWTR_nCK),
        .cfg_tFAW_nCK(w_config_regs__cfg_tFAW_nCK),
        .cfg_tRFC_nCK(w_config_regs__cfg_tRFC_nCK),
        .cfg_tWR_nCK(w_config_regs__cfg_tWR_nCK),
        .cfg_tRTP_nCK(w_config_regs__cfg_tRTP_nCK),
        .cfg_CL_nCK(w_config_regs__cfg_CL_nCK),
        .cfg_CWL_nCK(w_config_regs__cfg_CWL_nCK),
        .cfg_tCCD_nCK(w_config_regs__cfg_tCCD_nCK),
        .cfg_tREFI_nCK(w_config_regs__cfg_tREFI_nCK),
        .cfg_sched_policy(config_regs_cfg_sched_policy),
        .cfg_row_policy(config_regs_cfg_row_policy),
        .cfg_self_ref_mode(config_regs_cfg_self_ref_mode),
        .cfg_ecc_enable(config_regs_cfg_ecc_enable),
        .cfg_bist_start(config_regs_cfg_bist_start),
        .cfg_force_refresh(w_config_regs__cfg_force_refresh),
        .cfg_force_self_ref(config_regs_cfg_force_self_ref),
        .cfg_max_postpone(w_config_regs__cfg_max_postpone),
        .cfg_urgent_threshold(w_config_regs__cfg_urgent_threshold),
        .cfg_ref_priority(w_config_regs__cfg_ref_priority),
        .cfg_bist_pattern(config_regs_cfg_bist_pattern),
        .cfg_bist_addr_mode(config_regs_cfg_bist_addr_mode),
        .cfg_bist_addr_start(config_regs_cfg_bist_addr_start),
        .cfg_bist_addr_end(config_regs_cfg_bist_addr_end)
    );

    data_path u_data_path (
        .clk(clk),
        .rst_n(rst_n),
        .cmd_wr_valid(w_cmd_gen__fb_wr_valid),
        .cmd_rd_valid(w_cmd_gen__fb_rd_valid),
        .cmd_aux(w_cmd_gen__cmd_out_aux),
        .wr_data_valid(w_expr__data_path_wr_data_valid),
        .wr_data(w_wb_port__req_wdata),
        .wr_mask(w_wb_port__req_wmask),
        .wr_data_ready(data_path_wr_data_ready),
        .rd_rsp_valid(w_data_path__rd_rsp_valid),
        .rd_rsp_data(w_data_path__rd_rsp_data),
        .rd_rsp_aux(w_data_path__rd_rsp_aux),
        .cfg_CL_nCK(w_config_regs__cfg_CL_nCK),
        .cfg_CWL_nCK(w_config_regs__cfg_CWL_nCK),
        .ddr_dq_o(data_path_ddr_dq_o),
        .ddr_dq_oe(data_path_ddr_dq_oe),
        .ddr_dq_i(data_path_ddr_dq_i),
        .ddr_dm_o(data_path_ddr_dm_o),
        .ddr_dqs_o(data_path_ddr_dqs_o),
        .ddr_dqs_oe(data_path_ddr_dqs_oe),
        .ddr_dqs_i(data_path_ddr_dqs_i)
    );

    init_fsm u_init_fsm (
        .clk(clk),
        .rst_n(rst_n),
        .enable(init_fsm_enable),
        .init_done(w_init_fsm__init_done),
        .init_fail(w_init_fsm__init_fail),
        .init_cmd_valid(init_fsm_init_cmd_valid),
        .init_cmd(init_fsm_init_cmd),
        .init_addr(init_fsm_init_addr),
        .init_bank(init_fsm_init_bank),
        .init_cke(init_fsm_init_cke),
        .init_reset_n(init_fsm_init_reset_n),
        .init_state(init_fsm_init_state)
    );

    refresh_ctrl u_refresh_ctrl (
        .clk(clk),
        .rst_n(rst_n),
        .init_done(w_init_fsm__init_done),
        .cfg_force_refresh(w_config_regs__cfg_force_refresh),
        .cfg_tREFI_nCK(w_config_regs__cfg_tREFI_nCK),
        .cfg_max_postpone(w_config_regs__cfg_max_postpone),
        .cfg_urgent_threshold(w_config_regs__cfg_urgent_threshold),
        .cfg_ref_priority(w_config_regs__cfg_ref_priority),
        .ref_required(w_refresh_ctrl__ref_required),
        .ref_urgent(w_refresh_ctrl__ref_urgent),
        .ref_ack(w_scheduler__ref_ack),
        .ref_pending_cnt(w_refresh_ctrl__ref_pending_cnt),
        .ref_starve_flag(w_refresh_ctrl__ref_starve_flag)
    );

    scheduler u_scheduler (
        .clk(clk),
        .rst_n(rst_n),
        .q_valid(w_cmd_queue__entry_valid),
        .q_row(w_cmd_queue__entry_row),
        .q_col(w_cmd_queue__entry_col),
        .q_bank(w_cmd_queue__entry_bank),
        .q_we(w_cmd_queue__entry_we),
        .q_aux(w_cmd_queue__entry_aux),
        .bank_is_active(w_bank_tracker__bank_is_active),
        .bank_open_row(w_bank_tracker__bank_open_row),
        .bank_act_allowed(w_bank_tracker__bank_act_allowed),
        .bank_rd_allowed(w_bank_tracker__bank_rd_allowed),
        .bank_wr_allowed(w_bank_tracker__bank_wr_allowed),
        .bank_pre_allowed(w_bank_tracker__bank_pre_allowed),
        .ref_required(w_refresh_ctrl__ref_required),
        .ref_urgent(w_refresh_ctrl__ref_urgent),
        .ref_ack(w_scheduler__ref_ack),
        .cmd_valid(w_scheduler__cmd_valid),
        .cmd_type(w_scheduler__cmd_type),
        .cmd_row(w_scheduler__cmd_row),
        .cmd_col(w_scheduler__cmd_col),
        .cmd_bank(w_scheduler__cmd_bank),
        .cmd_we(w_scheduler__cmd_we),
        .cmd_aux(w_scheduler__cmd_aux),
        .deq_grant(w_scheduler__deq_grant),
        .deq_idx(w_scheduler__deq_idx)
    );

    wb_port u_wb_port (
        .clk(clk),
        .rst_n(rst_n),
        .wb_cyc_i(wb_port_wb_cyc_i),
        .wb_stb_i(wb_port_wb_stb_i),
        .wb_we_i(wb_port_wb_we_i),
        .wb_adr_i(wb_port_wb_adr_i),
        .wb_dat_i(wb_port_wb_dat_i),
        .wb_sel_i(wb_port_wb_sel_i),
        .wb_bte_i(wb_port_wb_bte_i),
        .wb_cti_i(wb_port_wb_cti_i),
        .wb_ack_o(wb_port_wb_ack_o),
        .wb_dat_o(wb_port_wb_dat_o),
        .wb_stall_o(wb_port_wb_stall_o),
        .wb_err_o(wb_port_wb_err_o),
        .req_valid(w_wb_port__req_valid),
        .req_we(w_wb_port__req_we),
        .req_addr(w_wb_port__req_addr),
        .req_wdata(w_wb_port__req_wdata),
        .req_wmask(w_wb_port__req_wmask),
        .req_aux(w_wb_port__req_aux),
        .req_ready(w_cmd_queue__enq_ready),
        .rsp_valid(w_data_path__rd_rsp_valid),
        .rsp_rdata(w_data_path__rd_rsp_data),
        .rsp_aux(w_data_path__rd_rsp_aux)
    );

endmodule
